"""
build_giapxac_batch1.py
Sinh file data/ocr_batches/giapxac_batch1.json từ dữ liệu bóc tách OCR sách scan
"Động vật chí Việt Nam - Tập 1: Tôm biển" (trang 32 đến 53).
Bao gồm 13 loài thuộc Họ Aristeidae và Họ Solenoceridae.
"""
import json
import os
from datetime import datetime, timezone

batch1_data = [
    {
        "id": "giapxac-species-1",
        "collection_id": "giap-xac",
        "volume": 1,
        "species_index": 1,
        "vn_name": "Tôm đỏ dẹp",
        "scientific_name": "Aristaeomorpha foliacea",
        "authorship": "(Risso, 1827)",
        "en_common_name": "Giant Red Shrimp",
        "tax_class_vn": "Lớp Giáp Xác",
        "tax_class_latin": "Malacostraca",
        "tax_order_vn": "Bộ Mười Chân",
        "tax_order_latin": "Decapoda",
        "tax_family_vn": "Họ Tôm Đỏ Gai",
        "tax_family_latin": "Aristeidae",
        "tax_genus_vn": "Giống tôm đỏ Aristaeomorpha Wood - Mason et Alcock, 1891",
        "tax_genus_latin": "Aristaeomorpha Wood - Mason et Alcock, 1891",
        "morphology_vn": "Chùy: Phát triển, mép dưới nằm ngang, thẳng, không có răng; mép trên của con cái có 8 - 13 răng, có 2 răng nằm trên vỏ đầu ngực; ở con đực ngắn, mép trên có 5 răng. Vỏ đầu ngực: Gờ sau chùy kéo dài đến giữa vỏ đầu ngực. Gờ bên chùy trán kéo dài đến mép hốc mắt. Phần bụng: Mặt lưng của các đốt bụng III - IV có gờ lưng, tận cùng của gờ lưng là 1 gai nhỏ. Đốt đuôi dài bằng 1,4 lần chiều dài đốt bụng, ở đoạn áp cuối mép bên có 3 đôi gai hoạt động. Trên mặt lưng đốt đuôi có 1 rãnh và 2 gờ dọc. Râu I: Sợi ngọn trên râu I ngắn, bằng 1/2 chiều dài cuống. Sợi ngọn dưới xuất phát từ cuối đốt thứ ba cuống râu I, dài hơn thân. Vảy râu II có chiều dài gấp đôi chiều rộng. Các chi và phần phụ: Chân bò IV và V nhỏ, dài và hình dạng sợi. Chân bò V kéo dài đến cuối đốt gốc cuống râu I. Mang nhánh ở chân bò III và chân bò IV phát triển. Petasma: Mặt lưng thùy bên và mép không có lông, thùy lưng hơi dẹp, dài, đoạn cuối hơi nhọn, kéo dài đến cuối thùy bên. Đoạn tiếp giáp bằng 5/6 chiều dài thùy. Mép dưới thùy bụng hơi nằm ngang và thẳng. Thùy bên to, rộng và dài; mép hai bên thẳng. Mặt bụng gần có dạng hình thang. Thelycum: Tấm nằm ngang giữa đôi chân bò IV có hình bán nguyệt, đoạn cuối hơi lồi, mép xung quanh hơi cong vào. Bề mặt phần giữa bằng phẳng, mép cuối có lông dài. Tấm bụng giữa đôi chân bò V rộng, ở giữa có một hình vuông hơi lõm, đoạn sau lồi về phía sau và nối liền với hạch lồi nằm ngang của đốt ngực cuối cùng.",
        "ecology_vn": "Sống ở độ sâu trên 200m, chất đáy bùn.",
        "economic_value_vn": "Tuy số lượng không nhiều, nhưng là loài tôm có kích thước tương đối lớn, dùng làm thực phẩm tốt.",
        "vn_size": "Chiều dài thân (Lt): 120 - 180mm.",
        "vn_distribution": "Thế giới: Từ vùng biển phía tây châu Phi, Địa Trung Hải đến Australia và Nhật Bản. Việt Nam: Vùng biển sâu Miền Trung.",
        "vn_specimen": "Nhiều mẫu lưu tại Viện Nghiên cứu hải sản Hải Phòng.",
        "vn_status": "",
        "conservation_status": "unknown",
        "synonyms": [
            "Penaeus foliacea Risso, 1827",
            "Aristeus foliaceus Smith, 1885",
            "Aristeus rostridentatus Bate, 1888",
            "Penaeopsis foliaceus Ortmann, 1890",
            "Aristaeomorpha giglioliana Wood-Mason, 1892",
            "Plesiopenaeus foliaceus Faxon, 1895",
            "Aristeus japonicus Yokoya, 1933"
        ],
        "worms_id": 158326,
        "worms_accepted_name": "Aristaeomorpha foliacea",
        "worms_status": "accepted",
        "worms_synced_at": datetime.now(timezone.utc).isoformat()
    },
    {
        "id": "giapxac-species-2",
        "collection_id": "giap-xac",
        "volume": 1,
        "species_index": 2,
        "vn_name": "Tôm đỏ biển sâu",
        "scientific_name": "Plesiopenaeus edwardsianus",
        "authorship": "(Johnson, 1867)",
        "en_common_name": "Scarlet Shrimp",
        "tax_class_vn": "Lớp Giáp Xác",
        "tax_class_latin": "Malacostraca",
        "tax_order_vn": "Bộ Mười Chân",
        "tax_order_latin": "Decapoda",
        "tax_family_vn": "Họ Tôm Đỏ Gai",
        "tax_family_latin": "Aristeidae",
        "tax_genus_vn": "Giống tôm đỏ biển sâu - Plesiopenaeus Bate, 1881",
        "tax_genus_latin": "Plesiopenaeus Bate, 1881",
        "morphology_vn": "Bề mặt thân vỏ bóng nhẵn. Khi trưởng thành, chùy ở con đực ngắn, mép trên chùy có 3 răng. Rãnh cổ rõ ràng hoặc chỉ có phần gốc rãnh. Có gai râu và gai vỏ mang, nhưng không có gai khoang mắt và gai gan. Sợi ngọn trên râu I ngắn, sợi ngọn dưới dạng sợi, nhỏ và dài. Phần bụng: Có gờ lưng từ đốt bụng III - VI, cuối cùng là một gai nhọn nhỏ. Góc dưới phía sau của tấm vỏ bên của các đốt bụng II - VI có một gai nhọn. Đốt đuôi dài bằng 1,2 lần đốt bụng VI. Rãnh dọc trên mặt lưng của đốt đuôi rộng, hai mép bên của rãnh có gờ. Phần áp cuối ở hai bên đốt đuôi có 4 đôi gai hoạt động. Các chi: Chân bò II có nhánh trên (epipodite), chân bò III có mang chân. Râu: Sợi ngọn trên râu I rộng, ngắn và dài bằng đốt gốc cuống râu I. Sợi ngọn dưới nhỏ dài hơn thân. Petasma: Mặt bụng và lưng trơn, bóng, mép biên không có lông hoặc gai. Thùy lưng hẹp, dài, đoạn cuối nhọn tù, hơi ngắn hơn thùy bên. Thùy bên to và rộng hơn thùy lưng, đoạn gốc rộng, đoạn cuối hẹp, mép cuối có một vết khía nhỏ. Thelycum: Túi nhận tinh do 4 tấm hợp thành. Tấm trước nằm giữa đôi chân bò IV có hình quả đào, tấm ngang nằm ở vỏ bụng, đoạn cuối to, mép hai bên phần gốc hơi lõm vào, mặt bụng phẳng và lõm xuống, bề mặt có một gờ dọc. Mặt lưng ở phần trước lồi, có dạng hình cầu. Chỗ lồi nằm giữa chân bò V có hình dáng như cái trống. Chỗ lồi nằm trên vỏ bụng, đoạn trước hẹp, tù, hai bên mép và đoạn cuối có lông, mặt bụng trơn bóng, không có lông. Giữa chân bò IV và V, ở hai bên có mấu lồi hình tam giác. Màu sắc: Lúc còn sống toàn thân có màu đỏ.",
        "ecology_vn": "Thường sống ở độ sâu trên 200 m, chất đáy bùn.",
        "economic_value_vn": "Là loài tôm có kích thước lớn thường gặp ở vùng biển sâu, có giá trị thực phẩm.",
        "vn_size": "Chiều dài thân (Lt): 190 - 315mm (con cái lớn hơn con đực).",
        "vn_distribution": "Thế giới: Vùng biển phía tây châu Phi từ Bồ Đào Nha đến Nam Phi. Từ quần đảo Anti đến Ấn Độ - Tây Thái Bình Dương. Từ bờ phía Đông châu Phi đến biển Andaman và Sumatra. Việt Nam: Vùng biển Miền Trung, ở độ sâu trên 200m.",
        "vn_specimen": "Nhiều mẫu lưu tại Viện Nghiên cứu hải sản Hải Phòng.",
        "vn_status": "",
        "conservation_status": "unknown",
        "synonyms": [
            "Penaeus edwardsianus Johnson, 1867",
            "Aristeus edwarsianus Miers, 1878",
            "Aristeus (Plesiopenaeus) edwardsianus Alcock, 1901",
            "Aristeus coralinus Bate, 1888"
        ],
        "worms_id": 210426,
        "worms_accepted_name": "Aristaeopsis edwardsiana",
        "worms_status": "superseded combination",
        "worms_synced_at": datetime.now(timezone.utc).isoformat()
    },
    {
        "id": "giapxac-species-3",
        "collection_id": "giap-xac",
        "volume": 1,
        "species_index": 3,
        "vn_name": "Tôm đỏ gai",
        "scientific_name": "Aristeus virilis",
        "authorship": "(Bate, 1881)",
        "en_common_name": "Stout Red Shrimp",
        "tax_class_vn": "Lớp Giáp Xác",
        "tax_class_latin": "Malacostraca",
        "tax_order_vn": "Bộ Mười Chân",
        "tax_order_latin": "Decapoda",
        "tax_family_vn": "Họ Tôm Đỏ Gai",
        "tax_family_latin": "Aristeidae",
        "tax_genus_vn": "Giống tôm lửa gai - Aristeus Duvernoy, 1840",
        "tax_genus_latin": "Aristeus Duvernoy, 1840",
        "morphology_vn": "Vỏ đầu ngực không có gai gan. Chân bò IV không có mang nhánh, chân bò III và đốt ngực VI không có mang chân. Chùy nằm ngang, thẳng. Ở con đực ngắn, chỉ dài đến cuối đốt II hoặc đốt III của cuống râu I. Ở con cái dài, nửa cuối hướng chếch lên. Mép trên có 3 răng, mép dưới không răng. Vỏ đầu ngực: Gờ sau chùy phát triển kéo dài đến 2/3 vỏ đầu ngực. Gờ cổ ngắn, nhưng rõ ràng. Rãnh cổ nông. Gờ gan rõ rệt, rãnh gan và rãnh mang tim phát triển, sâu và rộng hơn rãnh cổ. Trên vỏ đầu ngực có gai vỏ mang và gai râu. Không có gai gan. Góc hàm rộng, tròn. Phần bụng: Các đốt bụng I - III không có gờ lưng, nhưng mặt lưng các đốt bụng IV - VI có gờ dọc, cuối gờ hình thành gai nhọn. Đốt đuôi hơi dài hơn đốt bụng IV. Đốt đuôi nhọn, hai bên có 4 đôi gai hoạt động, ba đôi trước cách đôi trước hơi xa. Các chi: Cuối mép bụng đốt đùi chân bò I - III có 1 gai hoạt động. Năm đôi chân bò không có nhánh ngoài. Mặt bụng đốt bàn chân bò V có 10 gờ phát sáng. Râu: Sợi ngọn trên râu I ngắn hơn sợi ngọn dưới. Nhánh phụ mép trong cuống râu I thoái hóa. Phiến vảy râu II ở con đực và cái giống nhau. Petasma: Phiến lưng hẹp và dài, đoạn cuối nhọn khớp với đoạn cuối phiến bên. Phiến bên rộng hơn phiến lưng. Đoạn cuối phiến bên hơi tù, mép ngoài hình cánh cung. Thelycum: Phiến ngang giữa đôi chân bò IV phát triển, dạng hình viên trụ, hơi nghiêng, hai bên gốc hẹp và thẳng, mặt lưng hơi lồi, dạng trụ tròn, có lông. Hai bên của khoảng giữa chân bò IV và V có một phiến bên nhỏ, từ vỏ bụng phần gốc chân bò V lệch về phía trước sau đó cong qua 2 bên. Màu sắc: Vỏ và chân phụ phủ đầy lông. Thân có màu hồng.",
        "ecology_vn": "Thường gặp ở độ sâu trên 200 m chất đáy bùn - cát.",
        "economic_value_vn": "Là loài tôm kích thước lớn có giá trị thực phẩm, nhưng ít gặp.",
        "vn_size": "Chiều dài thân (Lt) thường gặp 80 - 161mm.",
        "vn_distribution": "Thế giới: Từ bờ phía đông châu Phi đến Nhật Bản, Philippin đến biển Andaman, Indonesia, Singapo và bắc Biển Đông. Việt Nam: Vùng biển sâu Quảng Nam - Đà Nẵng.",
        "vn_specimen": "Nhiều mẫu lưu tại Viện Nghiên cứu Hải sản Hải Phòng.",
        "vn_status": "",
        "conservation_status": "unknown",
        "synonyms": [
            "Hemipenaeus virilis Bate, 1881",
            "Aristaeus tomentosus Bate, 1881",
            "Hemipenaeus tomentosus Bate, 1881"
        ],
        "worms_id": 220251,
        "worms_accepted_name": "Aristeus virilis",
        "worms_status": "accepted",
        "worms_synced_at": datetime.now(timezone.utc).isoformat()
    },
    {
        "id": "giapxac-species-4",
        "collection_id": "giap-xac",
        "volume": 1,
        "species_index": 4,
        "vn_name": "Tôm lửa luca",
        "scientific_name": "Hadropenaeus lucasii",
        "authorship": "(Bate, 1881)",
        "en_common_name": "Trident Shrimp",
        "tax_class_vn": "Lớp Giáp Xác",
        "tax_class_latin": "Malacostraca",
        "tax_order_vn": "Bộ Mười Chân",
        "tax_order_latin": "Decapoda",
        "tax_family_vn": "Họ Tôm Lửa",
        "tax_family_latin": "Solenoceridae",
        "tax_genus_vn": "Giống tôm lửa vỏ dày - Hadropenaeus Perez-Farfante, 1977",
        "tax_genus_latin": "Hadropenaeus Perez-Farfante, 1977",
        "morphology_vn": "Chùy ngắn, không vượt quá đỉnh cuống râu I, chỉ có răng mép trên. Không có gai má và gai hốc mắt. Rãnh cổ dài gần tới gờ lưng, rãnh gan sâu. Sợi ngọn râu I dài hơn vỏ đầu ngực, có dạng hình trụ dẹp. Chùy tương đối ngắn, hình lưỡi dao, kéo dài đến gốc 2 râu I, mép trên 6 - 7 răng, mép dưới lồi, không răng. Vỏ đầu ngực: Nhìn từ mặt bên, gốc chùy trán tương đối sâu. Rãnh cổ sâu và dài, đạt đến gần giữa sống lưng vỏ đầu ngực, gờ cổ nhỏ nhưng rõ rệt. Có gai vỏ mang, gai trên gan, gai gan, gai râu, gai sau mắt và gai má. Gờ bên chùy trán kéo dài từ cuối đến mép trước vỏ đầu ngực. Rãnh gan phẳng từ gai vỏ mang đến phía sau gai gan. Phần bụng: Từ đốt III-VI có gờ lưng, cuối đốt VI có 1 gai nhỏ. Giữa mép sau gờ lưng đốt bụng III - V có khuyết lõm sâu. Đốt đuôi hơi dài hơn đốt bụng VI, có rãnh dọc lưng, 2 bên rãnh có gờ dọc, phần sau mép bên đốt đuôi có 1 đôi gai bất động. Các chi: Mép trong đốt đế chân bò V có một gai nhọn. 5 đôi chân bò đều có nhánh ngoài. Petasma: Phiến giữa lưng hơi rộng và dài, ở giữa phình to vượt quá mép ngoài của phiến bên. Mép đỉnh phiến bên và mép đỉnh phiến giữa bụng cùng nằm trên một mặt phẳng. Mép đỉnh phiến bên và phiến lưng có hàng lông cứng nhỏ. Thelycum: Dạng hở. Phần vỏ bụng ở giữa chân bò V phẳng. U lồi giữa mép trước tù, mép sau có 1 gờ ngang, trên gờ có lông dài. Giữa đôi chân bò IV có u ngang, lõm giữa, phần sau 2 mép bên hình thành u tròn. Màu sắc: Thân có màu hồng nhạt.",
        "ecology_vn": "Chưa rõ sinh học - sinh thái.",
        "economic_value_vn": "Kích thước nhỏ, sản lượng thấp.",
        "vn_size": "Chiều dài thân (Lt): 30 - 60mm.",
        "vn_distribution": "Thế giới: Phân bố tương đối rộng, từ vùng biển Madagasca đến Nhật Bản, Indonesia, Hawai và Trung Quốc. Việt Nam: Vịnh Bắc Bộ (Phạm Ngọc Đẳng, 1994).",
        "vn_specimen": "Nhiều mẫu lưu tại Viện Nghiên cứu hải sản Hải Phòng.",
        "vn_status": "",
        "conservation_status": "unknown",
        "synonyms": [
            "Solenocera lucasii Bate, 1881",
            "Philonicus lucassi Bate, 1888",
            "Pleoticus lucassi Bate, 1888",
            "Hymenopenaeus lucassi Kubo, 1949"
        ],
        "worms_id": 220283,
        "worms_accepted_name": "Hadropenaeus lucasii",
        "worms_status": "accepted",
        "worms_synced_at": datetime.now(timezone.utc).isoformat()
    },
    {
        "id": "giapxac-species-5",
        "collection_id": "giap-xac",
        "volume": 1,
        "species_index": 5,
        "vn_name": "Tôm lửa chùy dẹp",
        "scientific_name": "Haliporoides sibogae",
        "authorship": "(de Man, 1907)",
        "en_common_name": "Jack-knife Shrimp",
        "tax_class_vn": "Lớp Giáp Xác",
        "tax_class_latin": "Malacostraca",
        "tax_order_vn": "Bộ Mười Chân",
        "tax_order_latin": "Decapoda",
        "tax_family_vn": "Họ Tôm Lửa",
        "tax_family_latin": "Solenoceridae",
        "tax_genus_vn": "Giống tôm lửa chùy dẹp - Haliporoides Stebbing, 1914",
        "tax_genus_latin": "Haliporoides Stebbing, 1914",
        "morphology_vn": "Chùy đến hoặc vượt quá đốt II cuống râu, mép trên có răng, mép dưới cũng có loài có răng. Có gai râu, gai sau mắt, gai gan, gai trên gan, gai má. Không có gai khoang mắt và gai vỏ mang. Rãnh cổ sâu và dài đến sát gờ lưng vỏ đầu ngực. Rãnh gan dài, phần sau thẳng, phần trước cong xuống. Chùy: Có dạng hình cung, phần cuối thô và hơi cong xuống, mép trên 7 - 9 răng, mép dưới hơi lõm và có một viền lông dài. Vỏ đầu ngực: Gờ sau chùy rất ngắn, không rõ. Gờ và rãnh bên chùy rõ rệt kéo dài đến mép trước vỏ đầu ngực. Rãnh cổ sâu, kéo dài đến mép trước vỏ đầu ngực. Bộ phận gờ gan ở phía sau gai gan thẳng ngang, nhưng phần ở phía trước gai gan lệch xuống và kéo dài đến gốc gai má. Gờ phụ bên rất rõ. Phần bụng: Từ đốt IV - VI có gờ lưng, cuối gờ mỗi đốt hình thành 1 gai nhỏ. Đốt đuôi dài bằng đốt bụng VI. Mặt lưng đốt đuôi có 2 gờ dọc, ở giữa là rãnh dọc, gần cuối đốt đuôi có 1 đôi gai bất động. Mép bên nhánh đuôi ngoài có một gai phụ ở gần đầu nhọn. Các chi: Mép chân đốt đế chân bò IV, V đều có 1 u lồi, u này ở chân bò V của con đực rất phát triển thành hình phiến. Petasma: Phiến giữa lưng chỉ hợp lại ở gần gốc, phần giữa có lồi dài và cong vào trong, ngắn hơn phiến bên. Phiến giữa bụng ngắn, đỉnh không có các u nhỏ. Phiến bên hình tam giác, chiều dài gấp 2 lần chỗ rộng nhất; phiến bên hơi dài hơn phiến giữa, mặt lưng gốc phiến bên có 1 gai lồi hình trụ. Thelycum: Dạng hở. Phần vỏ bụng chân bò V có dạng vuông, chung quanh hơi lõm, phần giữa lồi. Vỏ bụng giữa chân bò IV có một phiến dọc lồi, đỉnh nhọn. Mép trong đốt đế chân bò IV có 1 gai nhỏ.",
        "ecology_vn": "Phân bố ở độ sâu 100 m - 1460 m, thường gặp ở độ sâu 350 - 600m (Theo L. B. Holthuis, 1980).",
        "economic_value_vn": "Có thể làm thực phẩm khi đánh bắt ở vùng biển sâu.",
        "vn_size": "Chiều dài thân (Lt): 60 - 145 mm.",
        "vn_distribution": "Thế giới: Các vùng biển Madagasca, Ấn Độ, Nhật Bản, Australia, New Zealand, Trung Quốc (Quảng Đông). Việt Nam: Vịnh Bắc Bộ (Phạm Ngọc Đẳng, 1994).",
        "vn_specimen": "Nhiều mẫu lưu tại Viện Nghiên cứu hải sản Hải Phòng.",
        "vn_status": "",
        "conservation_status": "unknown",
        "synonyms": [
            "Haliporus sibogae de Man, 1907",
            "Hymenopenaeus sibogae Burkenroad, 1936",
            "Parahaliporus sibogae Kubo, 1949",
            "Haliporoides sibogae Pérez-Farfante, 1977"
        ],
        "worms_id": 220285,
        "worms_accepted_name": "Haliporoides sibogae",
        "worms_status": "accepted",
        "worms_synced_at": datetime.now(timezone.utc).isoformat()
    },
    {
        "id": "giapxac-species-6",
        "collection_id": "giap-xac",
        "volume": 1,
        "species_index": 6,
        "vn_name": "Tôm lửa ống",
        "scientific_name": "Solenocera crassicornis",
        "authorship": "(H. Milne Edwards, 1837)",
        "en_common_name": "Coastal mud Shrimp",
        "tax_class_vn": "Lớp Giáp Xác",
        "tax_class_latin": "Malacostraca",
        "tax_order_vn": "Bộ Mười Chân",
        "tax_order_latin": "Decapoda",
        "tax_family_vn": "Họ Tôm Lửa",
        "tax_family_latin": "Solenoceridae",
        "tax_genus_vn": "Giống tôm Lửa - Solenocera H. Lucas, 1849",
        "tax_genus_latin": "Solenocera H. Lucas, 1849",
        "morphology_vn": "Chùy ngắn, mép trên có răng, mép dưới không răng. Có gai râu, gai sau mắt, gai gan. Mép cuối đốt đuôi (con trưởng thành) không có gai bất động. Mép trong cuống râu I có nhánh phụ, sợi ngọn trên hẹp, phẳng, sợi ngọn dưới rộng có dạng hình trụ dẹp, mặt ngoài hơi phình, sợi ngọn dài hơn vỏ đầu ngực. Chùy hơi vượt quá đỉnh mắt, mép trên có 8 - 10 gai (thường là 9 gai), mép dưới không có gai. Vỏ đầu ngực: Gờ sau chùy rất thấp (không rãnh giữa) kéo dài đến mép sau vỏ đầu ngực. Rãnh cổ sâu và rộng, phần trên lệch đến phần lưng. Ở giữa phần sau gai sau mắt và gai gan có 1 rãnh sâu nối liền với rãnh cổ và rãnh gan ở phía trước gai gan. Phần sau rãnh gan phẳng, phần trước lệch xuống. Phần bụng: Từ đốt bụng I - VI có gờ lưng, 3 gờ sau cao và sắc hơn. Cuối gờ lưng và hai góc bên của đốt VI đều có 1 gai nhỏ. Mép bên đốt đuôi thường không có gai nhọn, ở cá thể nhỏ có thể thấy những gai bất động rất nhỏ. Các chi: Sợi ngọn trên và dưới của râu I bằng nhau, bằng 1,2 đến 2 lần vỏ đầu ngực, theo sự tăng trưởng tỷ lệ này giảm xuống. Vảy râu II tương đối dài, vượt quá cuống râu I, đỉnh vảy tròn. Petasma: Phiến giữa vượt quá đỉnh phiến bên, mép đỉnh không có gai hoặc lông nhỏ. Mép đỉnh phiến lưng bên có 20 - 28 gai nhỏ. Gần đỉnh phiến bụng bên có 2 u lồi nhỏ, u ở gần góc của mép bên lưng lớn hơn. Mép bụng phiến bên có 1 u lồi dạng thìa đoạn cuối cong ra ngoài, không có gai hoặc lông cứng. Thelycum: Đốt đế đôi chân bò IV phát triển, mép sau hình thành góc lồi. Trên vỏ bụng đốt ngực cuối, có 1 gờ dọc ở phần giữa khu lồi vuông, ở giữa gờ lồi này có u lồi hình viên trụ, trên bề mặt có nhiều lông cứng. Giữa phía trước mép trước khu lồi vuông có 2 u lồi với nhiều lông nhỏ. Màu sắc: Vỏ nhẵn bóng, màu hồng cam nhạt.",
        "ecology_vn": "Sống ở vùng có chất đáy bùn cát, độ sâu 40 - 50 m.",
        "economic_value_vn": "Có thể làm thực phẩm, thường thu được trong lưới giã cào, số lượng không lớn.",
        "vn_size": "Đã gặp các cá thể có chiều dài thân (Lt): 50 - 80 mm.",
        "vn_distribution": "Thế giới: Ấn Độ, Pakistan, Nhật Bản, Trung Quốc, Indonesia, Malaysia. Việt Nam: Vịnh Bắc Bộ.",
        "vn_specimen": "Nhiều mẫu lưu tại Phân viện Hải dương học Hải Phòng.",
        "vn_status": "",
        "conservation_status": "unknown",
        "synonyms": [
            "Penaeus crassicornis H. M. Edwards, 1837",
            "Solenocera sinensis Yu, 1937",
            "Solenocera indica Nataraj, 1945",
            "Solenocera subnuda Kubo, 1949",
            "Solenocera kuboi Hall, 1956"
        ],
        "worms_id": 107119,
        "worms_accepted_name": "Solenocera crassicornis",
        "worms_status": "accepted",
        "worms_synced_at": datetime.now(timezone.utc).isoformat()
    },
    {
        "id": "giapxac-species-7",
        "collection_id": "giap-xac",
        "volume": 1,
        "species_index": 7,
        "vn_name": "Tôm lửa Trung Hoa",
        "scientific_name": "Solenocera koelbeli",
        "authorship": "de Man, 1911",
        "en_common_name": "Chinese mud Shrimp",
        "tax_class_vn": "Lớp Giáp Xác",
        "tax_class_latin": "Malacostraca",
        "tax_order_vn": "Bộ Mười Chân",
        "tax_order_latin": "Decapoda",
        "tax_family_vn": "Họ Tôm Lửa",
        "tax_family_latin": "Solenoceridae",
        "tax_genus_vn": "Giống tôm Lửa - Solenocera H. Lucas, 1849",
        "tax_genus_latin": "Solenocera H. Lucas, 1849",
        "morphology_vn": "Chùy: Ngắn, không tới đỉnh mắt, mép trên 6 - 8 răng. Vỏ đầu ngực: Gờ sau chùy cao và sắc, có dạng phiến lồi, kéo dài đến mép sau vỏ đầu ngực, có rãnh giữa nông. Phần trên rãnh cổ vượt qua gờ sau chùy, hình thành khuyết nhỏ. Bộ phận gờ gan ở phía trước gai gan rõ ràng, lệch xuống về phía trước, sau đó uốn cong đến gần góc má. Phần bụng: Từ đốt bụng III - VI có gờ lưng. Cuối gờ lưng và mép sau bên đốt VI đều có 1 gai nhỏ. Gần cuối đốt đuôi có 1 đôi gai bất động. Các chi: Sợi ngọn râu I rộng, sợi ngọn trên và dưới dài bằng nhau và bằng 1,3 lần chiều dài vỏ đầu ngực. Petasma: Đỉnh phiến giữa và phiến bên cao bằng nhau. Mép phiến lưng bên có 19 - 23 gai nhỏ. Mép bụng phiến bên có 1 u lồi dạng thìa, mép cuối cong xuống phía ngoài, có 12 - 14 lông gai. Mặt lưng phiến bụng bên không có u lồi. Thelycum: Vỏ bụng giữa đôi chân bò IV có một tấm ngang dạng hình thang, mép trước lõm, mặt bụng có 1 rãnh dọc, mép sau lồi hình thành 2 nửa hình tròn, ở giữa lõm dần về phía trước. Vỏ bụng ở đốt cuối có gờ thấp hình thành hình vuông lõm, mép trước đến phần gốc chân bò IV. Màu sắc: Vỏ nhẵn bóng, màu hồng cam nhạt.",
        "ecology_vn": "Thường phân bố ở vùng biển sâu 60 - 90 m.",
        "economic_value_vn": "Có thể làm thực phẩm nhưng số lượng ít.",
        "vn_size": "Đã gặp các cá thể có chiều dài thân (Lt): 50 - 80mm.",
        "vn_distribution": "Thế giới: Các vùng biển Triều Tiên, Nhật Bản, Indonesia, Trung Quốc. Việt Nam: Vịnh Bắc Bộ.",
        "vn_specimen": "Nhiều mẫu lưu tại Viện Động vật, Viện Hàn lâm Khoa học Liên bang Nga, Phân viện Hải dương học Hải Phòng.",
        "vn_status": "",
        "conservation_status": "unknown",
        "synonyms": [
            "Solenocera koelbeli de Man, 1911",
            "Solenocera depressa Kubo, 1949"
        ],
        "worms_id": 210422,
        "worms_accepted_name": "Solenocera koelbeli",
        "worms_status": "accepted",
        "worms_synced_at": datetime.now(timezone.utc).isoformat()
    },
    {
        "id": "giapxac-species-8",
        "collection_id": "giap-xac",
        "volume": 1,
        "species_index": 8,
        "vn_name": "Tôm lửa Việt Nam",
        "scientific_name": "Solenocera vietnamensis",
        "authorship": "Starobogatov, 1972",
        "en_common_name": "Vietnamese Shrimp",
        "tax_class_vn": "Lớp Giáp Xác",
        "tax_class_latin": "Malacostraca",
        "tax_order_vn": "Bộ Mười Chân",
        "tax_order_latin": "Decapoda",
        "tax_family_vn": "Họ Tôm Lửa",
        "tax_family_latin": "Solenoceridae",
        "tax_genus_vn": "Giống tôm Lửa - Solenocera H. Lucas, 1849",
        "tax_genus_latin": "Solenocera H. Lucas, 1849",
        "morphology_vn": "Chùy: Ngắn, mép trên có 9 răng. Vỏ đầu ngực: Gờ sau chùy tương đối cao, Kéo dài đến mép sau vỏ đầu ngực. Rãnh cổ rõ ràng nhưng chưa đạt đến giữa gờ sau chùy. Bộ phận gờ gan ở phía trước gai gan lệch xuống và kéo dài đến gần góc má hình thành cung nhỏ. Phần bụng: Từ đốt bụng IV - VI có gờ lưng và mép sau bên đều có gai nhỏ. Gần cuối đốt đuôi có một đôi gai bất động. Các chi: Chân bò I có đôi gai ở đốt đùi và đốt gốc, chân bò II chỉ có gai đốt gốc. Petasma và thelycum có cấu tạo đặc trưng.",
        "ecology_vn": "Thường sống ở độ sâu 32 - 113 m, có chất đáy bùn cát (Starobogatov, 1972).",
        "economic_value_vn": "Có thể sử dụng làm thực phẩm, số lượng ít.",
        "vn_size": "Chiều dài thân (Lt): 50 - 75 mm.",
        "vn_distribution": "Thế giới: Không rõ. Việt Nam: Vịnh Bắc Bộ.",
        "vn_specimen": "Typ: Holotyp đực; lưu giữ ở Viện Động vật, Viện Hàn lâm Khoa học Liên bang Nga, No 1/47728. Nhiều mẫu lưu tại Viện Động vật Nga.",
        "vn_status": "",
        "conservation_status": "unknown",
        "synonyms": [
            "Solenocera vietnamensis Starobogatov, 1972"
        ],
        "worms_id": 585511,
        "worms_accepted_name": "Solenocera koelbeli",
        "worms_status": "junior subjective synonym",
        "worms_synced_at": datetime.now(timezone.utc).isoformat()
    },
    {
        "id": "giapxac-species-9",
        "collection_id": "giap-xac",
        "volume": 1,
        "species_index": 9,
        "vn_name": "Tôm lửa đất",
        "scientific_name": "Solenocera pectinata",
        "authorship": "(Bate, 1888)",
        "en_common_name": "Comb Shrimp",
        "tax_class_vn": "Lớp Giáp Xác",
        "tax_class_latin": "Malacostraca",
        "tax_order_vn": "Bộ Mười Chân",
        "tax_order_latin": "Decapoda",
        "tax_family_vn": "Họ Tôm Lửa",
        "tax_family_latin": "Solenoceridae",
        "tax_genus_vn": "Giống tôm Lửa - Solenocera H. Lucas, 1849",
        "tax_genus_latin": "Solenocera H. Lucas, 1849",
        "morphology_vn": "Chùy: Ngắn phần giữa hơi lồi, đỉnh chùy hơi lệch xuống, mép trên 6 - 9 răng, mép dưới phình và không răng, phần chùy nhọn hơi cong xuống. Vỏ đầu ngực: Gờ sau chùy rất ngắn chỉ đến giữa vỏ đầu ngực. Rãnh cổ rộng và sâu, vượt qua gờ sau chùy. Rãnh gan rất rõ, gờ gan thẳng, phần trước thô, đến khu má đột nhiên cong xuống dưới. Gờ cổ nhỏ và sắc. Phần bụng: Từ giữa đốt bụng III - VI có gờ lưng, cuối gờ lưng và góc dưới sau đốt bụng đều có gai nhỏ. Đốt đuôi dài bằng đốt bụng VI, gần cuối hai bên đều có 1 gai bất động. Các chi: Sợi ngọn râu I dẹp, sợi ngọn trên dưới bằng nhau, ở con đực bằng 1,1 - 1,2 chiều dài vỏ đầu ngực; ở con cái sợi ngọn râu I lại bằng vỏ đầu ngực, sợi ngọn trên rộng hơn sợi ngọn dưới, 4 đốt cuối trở nên nhỏ và nhọn rõ rệt như dạng sợi. Chỉ có chân bò I có gai đốt gốc và gai đốt đùi. Petasma: Phiến lưng giữa ngắn hơn phiến bụng giữa rõ rệt. Phiến bụng giữa có khoảng hơn 20 gai nhọn, mép cuối của phiến lưng bên có khoảng 24 - 31 gai nhọn, gai ở hai đầu ngắn và nhỏ. Hai bên mặt lưng của phiến bên có 1 phiến lồi, mép ngoài có khoảng 20 gai nhỏ, mặt bụng phiến bên có 1 u lồi dạng thìa, đoạn cuối cong xuống và không có gai nhỏ. Thelycum: Vỏ bụng giữa đôi chân bò IV hơi gồ lên, mép sau có phiến dạng hình thang, ở giữa có rãnh dọc. Vỏ bụng giữa đôi chân bò V có gờ thấp hình thành hình vuông. Phía trước của mép trước có 4 u lồi nhỏ mang nhiều lông dài. Giữa mép trước khu hình vuông có 1 u lồi nhỏ, trong khu vuông có một đôi u tròn, giữa 2 u có một rãnh dọc sâu. Màu sắc: Vỏ nhẵn bóng, không có lông.",
        "ecology_vn": "Thường phân bố ở độ sâu 35 - 86m, đáy bùn cát (Starobogatov, 1972).",
        "economic_value_vn": "Có thể làm thực phẩm, nhưng số lượng không nhiều.",
        "vn_size": "Chiều dài thân (Lt): 26 - 50 mm.",
        "vn_distribution": "Thế giới: Từ các vùng biển phía đông châu Phi đến Malaysia, Nhật Bản, Trung Quốc. Việt Nam: Vịnh Bắc Bộ.",
        "vn_specimen": "Nhiều mẫu lưu tại Viện Động vật, Viện Hàn lâm Khoa học Liên bang Nga, Phân viện Hải dương học Hải Phòng.",
        "vn_status": "",
        "conservation_status": "unknown",
        "synonyms": [
            "Philonicus pectinatus Bate, 1888",
            "Solenocera pectinulata Kubo, 1949"
        ],
        "worms_id": 210415,
        "worms_accepted_name": "Solenocera pectinata",
        "worms_status": "accepted",
        "worms_synced_at": datetime.now(timezone.utc).isoformat()
    },
    {
        "id": "giapxac-species-10",
        "collection_id": "giap-xac",
        "volume": 1,
        "species_index": 10,
        "vn_name": "Tôm lửa bêđô",
        "scientific_name": "Solenocera bedokensis",
        "authorship": "Hall, 1962",
        "en_common_name": "Bedoken Shrimp",
        "tax_class_vn": "Lớp Giáp Xác",
        "tax_class_latin": "Malacostraca",
        "tax_order_vn": "Bộ Mười Chân",
        "tax_order_latin": "Decapoda",
        "tax_family_vn": "Họ Tôm Lửa",
        "tax_family_latin": "Solenoceridae",
        "tax_genus_vn": "Giống tôm Lửa - Solenocera H. Lucas, 1849",
        "tax_genus_latin": "Solenocera H. Lucas, 1849",
        "morphology_vn": "Chùy: Ngắn nằm ngang, mép trên có 7 răng. Vỏ đầu ngực: Gờ sau chùy ngắn, phẳng. Rãnh cổ sâu, nhưng chưa đạt đến phần giữa của gờ sau chùy. Rãnh và gờ gan rõ. Phần gờ gan ở phía sau gai gan phẳng, phần phía trước cong lệch xuống góc má, nhưng không hình thành cung. Phần bụng: Từ đốt bụng III - VI có gờ lưng. Cuối gờ lưng và mép sau bên đốt bụng VI có gai nhỏ. Đốt đuôi có 1 đôi gai bất động. Các chi: Chân bò I, II có gai đốt gốc và gai đốt đùi.",
        "ecology_vn": "Thường phân bố ở độ sâu 24 - 76 m, đáy bùn cát.",
        "economic_value_vn": "Không đáng kể.",
        "vn_size": "Chiều dài thân (Lt): 30 - 40mm.",
        "vn_distribution": "Thế giới: Singapo. Việt Nam: Vịnh Bắc Bộ.",
        "vn_specimen": "Nhiều mẫu lưu tại Viện Động vật, Viện Hàn lâm Khoa học Liên bang Nga.",
        "vn_status": "",
        "conservation_status": "unknown",
        "synonyms": [
            "Solenocera bedokensis Hall, 1962"
        ],
        "worms_id": 210423,
        "worms_accepted_name": "Solenocera bedokensis",
        "worms_status": "accepted",
        "worms_synced_at": datetime.now(timezone.utc).isoformat()
    },
    {
        "id": "giapxac-species-11",
        "collection_id": "giap-xac",
        "volume": 1,
        "species_index": 11,
        "vn_name": "Tôm lửa gura",
        "scientific_name": "Solenocera gurjanovae",
        "authorship": "Starobogatov, 1972",
        "en_common_name": "Gurjanovae Shrimp",
        "tax_class_vn": "Lớp Giáp Xác",
        "tax_class_latin": "Malacostraca",
        "tax_order_vn": "Bộ Mười Chân",
        "tax_order_latin": "Decapoda",
        "tax_family_vn": "Họ Tôm Lửa",
        "tax_family_latin": "Solenoceridae",
        "tax_genus_vn": "Giống tôm Lửa - Solenocera H. Lucas, 1849",
        "tax_genus_latin": "Solenocera H. Lucas, 1849",
        "morphology_vn": "Chùy: Ngắn nằm ngang, mép trên có 8 gai. Vỏ đầu ngực: Gờ sau chùy ngắn, phẳng. Rãnh cổ sâu và vượt qua phần giữa của gờ sau chùy. Rãnh và gờ gan phía sau gan không rõ, phần phía trước gai gan rõ, lệch xuống và kéo dài đến gần góc mang. Phần bụng: Từ giữa đốt bụng III - VI có gờ lưng. Cuối gờ lưng và mép bên sau đốt bụng VI đều có 1 gai nhỏ. Đốt đuôi ngắn, gần cuối có 1 đốt gai bất động. Các chi: Chân bò I có gai đốt gốc và gai đốt đùi.",
        "ecology_vn": "Mẫu thu được ở độ sâu 13 - 58 m, chất đáy bùn cát hoặc cát.",
        "economic_value_vn": "Cá thể nhỏ, ít gặp nên ít có giá trị kinh tế.",
        "vn_size": "Chiều dài thân (Lt): 18 - 22 mm.",
        "vn_distribution": "Thế giới: Không rõ. Việt Nam: Vịnh Bắc Bộ.",
        "vn_specimen": "Typ: Holotyp, con đực, lưu giữ ở Viện Động vật, Viện Hàn lâm Khoa học Liên bang Nga, No 1/47729. Nhiều mẫu lưu tại Viện Động vật Nga.",
        "vn_status": "",
        "conservation_status": "unknown",
        "synonyms": [
            "Solenocera gurjanovae Starobogatov, 1972"
        ],
        "worms_id": 377666,
        "worms_accepted_name": "Solenocera gurjanovae",
        "worms_status": "accepted",
        "worms_synced_at": datetime.now(timezone.utc).isoformat()
    },
    {
        "id": "giapxac-species-12",
        "collection_id": "giap-xac",
        "volume": 1,
        "species_index": 12,
        "vn_name": "Tôm lửa phương gi",
        "scientific_name": "Solenocera phuongi",
        "authorship": "Starobogatov, 1972",
        "en_common_name": "Phuongi Shrimp",
        "tax_class_vn": "Lớp Giáp Xác",
        "tax_class_latin": "Malacostraca",
        "tax_order_vn": "Bộ Mười Chân",
        "tax_order_latin": "Decapoda",
        "tax_family_vn": "Họ Tôm Lửa",
        "tax_family_latin": "Solenoceridae",
        "tax_genus_vn": "Giống tôm Lửa - Solenocera H. Lucas, 1849",
        "tax_genus_latin": "Solenocera H. Lucas, 1849",
        "morphology_vn": "Chùy: Ngắn nằm ngang, mép trên có 7 gai. Vỏ đầu ngực: Gờ sau chùy ngắn, phẳng. Rãnh cổ sâu và rõ nhưng chưa đạt tới giữa gờ sau chùy. Có thể nhận biết được phần gờ ở phía sau gai gan, phần phía trước gai gan rõ rệt, đột ngột lệch xuống phía dưới gần tới góc má. Phần bụng: Từ đốt bụng IV - VI có gờ lưng. Cuối gờ lưng và hai bên sau đốt bụng IV đều có gai nhỏ. Đốt đuôi ngắn và có 1 đôi gai bất động. Các chi: Đôi chân bò I có gai đốt gốc và gai đốt đùi.",
        "ecology_vn": "Mẫu thu được ở độ sâu 113m, chất đáy bùn cát.",
        "economic_value_vn": "Ít gặp, cá thể nhỏ.",
        "vn_size": "Chiều dài thân (Lt) 17mm.",
        "vn_distribution": "Thế giới: Không rõ. Việt Nam: Vịnh Bắc Bộ.",
        "vn_specimen": "Typ: Holotyp, con cái, lưu giữ ở Viện Động vật, Viện Hàn lâm Khoa học Liên bang Nga No 1/47730. Nhiều mẫu lưu tại Viện Động vật Nga.",
        "vn_status": "",
        "conservation_status": "unknown",
        "synonyms": [
            "Solenocera phuongi Starobogatov, 1972"
        ],
        "worms_id": 377674,
        "worms_accepted_name": "Solenocera phuongi",
        "worms_status": "accepted",
        "worms_synced_at": datetime.now(timezone.utc).isoformat()
    },
    {
        "id": "giapxac-species-13",
        "collection_id": "giap-xac",
        "volume": 1,
        "species_index": 13,
        "vn_name": "Tôm lửa zaren",
        "scientific_name": "Solenocera zarenkovi",
        "authorship": "Starobogatov, 1972",
        "en_common_name": "Zarenkov Shrimp",
        "tax_class_vn": "Lớp Giáp Xác",
        "tax_class_latin": "Malacostraca",
        "tax_order_vn": "Bộ Mười Chân",
        "tax_order_latin": "Decapoda",
        "tax_family_vn": "Họ Tôm Lửa",
        "tax_family_latin": "Solenoceridae",
        "tax_genus_vn": "Giống tôm Lửa - Solenocera H. Lucas, 1849",
        "tax_genus_latin": "Solenocera H. Lucas, 1849",
        "morphology_vn": "Chùy: Ngắn, nằm ngang, mép trên có 7 gai. Vỏ đầu ngực: Gờ sau chùy trán ngắn, phẳng. Rãnh cổ ngắn. Chiếm khoảng 3/4 khoảng cách từ gai gan đến giữa gờ sau chùy. Toàn bộ gờ gan đều phát triển, phần trước gai gan đều phát triển về phía trước và từ từ chếch xuống đến gần khu má. Phần bụng: Từ đốt bụng III - VI có gờ lưng. Cuối gờ lưng và hai bên sau đốt bụng VI đều có 1 gai nhỏ. Đốt đuôi có 1 đôi gai bất động. Các chi: Chân bò I chỉ đến đỉnh cuống râu I.",
        "ecology_vn": "Mẫu thu được ở độ sâu trên 30m, đáy bùn.",
        "economic_value_vn": "Không đáng kể.",
        "vn_size": "Chiều dài thân (Lt) 20mm.",
        "vn_distribution": "Thế giới: Chưa rõ. Việt Nam: Vịnh Bắc Bộ.",
        "vn_specimen": "Typ: Holotyp, con cái, lưu giữ ở Viện Động vật, Viện Hàn lâm Khoa học Liên bang Nga No 1/47731. Nhiều mẫu lưu tại Viện Động vật Nga.",
        "vn_status": "",
        "conservation_status": "unknown",
        "synonyms": [
            "Solenocera zarenkovi Starobogatov, 1972"
        ],
        "worms_id": 377678,
        "worms_accepted_name": "Solenocera zarenkovi",
        "worms_status": "accepted",
        "worms_synced_at": datetime.now(timezone.utc).isoformat()
    }
]

out_path = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "data", "ocr_batches", "giapxac_batch1.json")
with open(out_path, "w", encoding="utf-8") as f:
    json.dump(batch1_data, f, ensure_ascii=False, indent=2)

print(f"✓ Đã tạo thành công {out_path} với {len(batch1_data)} loài.")
