#!/usr/bin/env python3
"""
scripts/upsert_marine_mammals.py
---------------------------------
Khởi tạo và Upsert dữ liệu Thú biển Việt Nam (collection: 'thu-bien'):
1. Cập nhật bảng `collections` với `id: 'thu-bien'`.
2. Cập nhật bảng `literature_sources` với đầu sách đại diện:
   "Danh lục Thú biển Việt Nam & Mẫu vật Lăng Ông"
   (Smith et al. 1995; McGowen, Vũ Long et al. 2021; Viện Hải dương học).
   Nhà xuất bản: NXB Khoa học và Kỹ thuật.
3. Upsert 34 loài Thú biển Việt Nam (1 loài Bò biển Sirenia + 33 loài nhóm Cá voi Cetacea)
   kèm taxonomy 7 cấp, mô tả hình thái, ghi chú mẫu vật Lăng Ông / mắc cạn, phân bố và trích dẫn khoa học.

Tác giả: Antigravity Assistant cho chú Chình
Ngày tạo: 13/09/2026
"""

import os
import sys
import json
import urllib.request
from pathlib import Path
from dotenv import load_dotenv

sys.stdout.reconfigure(encoding='utf-8', line_buffering=True)

BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / ".env.local")
load_dotenv(BASE_DIR / ".env")

SUPABASE_URL = os.environ.get("NEXT_PUBLIC_SUPABASE_URL") or os.environ.get("SUPABASE_URL")
SERVICE_KEY = os.environ.get("SUPABASE_SERVICE_ROLE_KEY") or os.environ.get("SUPABASE_SERVICE_KEY")

if not SUPABASE_URL or not SERVICE_KEY:
    print("❌ Lỗi: Không tìm thấy SUPABASE_URL hoặc SUPABASE_SERVICE_ROLE_KEY!")
    sys.exit(1)

HEADERS_SUPA = {
    "apikey": SERVICE_KEY,
    "Authorization": f"Bearer {SERVICE_KEY}",
    "Content-Type": "application/json",
    "Prefer": "return=representation"
}

# ── 1. Cập nhật bảng collections ─────────────────────────────────────
def setup_collection():
    print("\n--- 1. CẬP NHẬT BẢNG COLLECTIONS ---")
    url = f"{SUPABASE_URL}/rest/v1/collections"
    
    collection_data = {
        "id": "thu-bien",
        "slug": "thu-bien",
        "name_vn": "Thú biển",
        "name_en": "Marine Mammals of Vietnam",
        "icon": "🐋",
        "accent_color": "#38bdf8",
        "volume_count": 1,
        "status": "active",
        "sort_order": 8
    }
    
    req = urllib.request.Request(
        f"{url}?on_conflict=id",
        headers={**HEADERS_SUPA, "Prefer": "resolution=merge-duplicates,return=representation"},
        data=json.dumps(collection_data).encode("utf-8"),
        method="POST"
    )
    with urllib.request.urlopen(req) as r:
        print("✅ Đã thiết lập collection 'thu-bien' trong database.")

# ── 2. Cập nhật bảng literature_sources ──────────────────────────────
def setup_literature():
    print("\n--- 2. CẬP NHẬT BẢNG LITERATURE_SOURCES ---")
    url = f"{SUPABASE_URL}/rest/v1/literature_sources"
    
    # Check if already exists
    check_req = urllib.request.Request(f"{url}?title=eq.Danh%20l%E1%BB%A5c%20Th%C3%BA%20bi%E1%BB%83n%20Vi%E1%BB%87t%20Nam%20%26%20M%E1%BA%ABu%20v%E1%BA%ADt%20L%C4%83ng%20%C3%94ng", headers=HEADERS_SUPA)
    exists = False
    try:
        with urllib.request.urlopen(check_req) as r:
            rows = json.loads(r.read().decode("utf-8"))
            exists = len(rows) > 0
    except Exception:
        pass

    lit_data = {
        "title": "Danh lục Thú biển Việt Nam & Mẫu vật Lăng Ông",
        "subtitle": "Smith et al. 1995; McGowen, Vũ Long et al. 2021",
        "author": "Smith et al. 1995; McGowen, Vũ Long et al. 2021; Viện Hải dương học",
        "publisher": "NXB Khoa học và Kỹ thuật",
        "year": "1995 – 2021",
        "stats_count": "34 loài",
        "pill_text": "Chuyên khảo (34 loài)",
        "description": "Công trình tổng hợp, định loại và hệ thống hóa toàn diện các loài Thú biển (Bò biển, Cá voi tấm sừng hàm, Cá nhà táng, Cá voi có mỏ và Cá heo) ghi nhận tại các vùng biển Việt Nam thông qua khảo sát thực địa, mẫu vật lịch sử lưu giữ tại các Đền thờ Cá Ông (Lăng Ông) và các dữ liệu cứu hộ thú biển mắc cạn.",
        "href": "/thu-bien",
        "chips": ["Bò biển", "Cá voi", "Cá nhà táng", "Cá heo", "Lăng Ông", "Cứu hộ mắc cạn"],
        "icon_name": "waves",
        "sort_order": 8,
        "is_visible": True
    }
    
    if exists:
        req = urllib.request.Request(
            f"{url}?title=eq.Danh%20l%E1%BB%A5c%20Th%C3%BA%20bi%E1%BB%83n%20Vi%E1%BB%87t%20Nam%20%26%20M%E1%BA%ABu%20v%E1%BA%ADt%20L%C4%83ng%20%C3%94ng",
            headers={**HEADERS_SUPA, "Prefer": "return=representation"},
            data=json.dumps(lit_data).encode("utf-8"),
            method="PATCH"
        )
    else:
        req = urllib.request.Request(
            url,
            headers={**HEADERS_SUPA, "Prefer": "return=representation"},
            data=json.dumps(lit_data).encode("utf-8"),
            method="POST"
        )
    try:
        with urllib.request.urlopen(req) as r:
            print("✅ Đã thêm/cập nhật tài liệu nguồn 'Danh lục Thú biển Việt Nam & Mẫu vật Lăng Ông' vào database.")
    except Exception as e:
        print(f"ℹ️ Lưu ý khi cập nhật literature_sources: {e}")

# ── 3. Danh sách 34 loài Thú biển Việt Nam ────────────────────────────
MARINE_MAMMALS = [
    # ── BỘ SIRENIA (Bộ Bò biển) ──
    {
        "id": "thubien-species-1",
        "collection_id": "thu-bien",
        "volume": 1,
        "species_index": 1,
        "vn_name": "Bò biển",
        "scientific_name": "Dugong dugon",
        "authorship": "(Müller, 1776)",
        "en_common_name": "Dugong",
        "vn_alternate_names": "Cá cúi, Cá nàng tiên",
        "tax_class_vn": "Lớp Thú (Động vật có vú)",
        "tax_class_latin": "Mammalia",
        "tax_order_vn": "Bộ Bò biển",
        "tax_order_latin": "Sirenia",
        "tax_family_vn": "Họ Bò biển",
        "tax_family_latin": "Dugongidae",
        "tax_genus_vn": "Chi Bò biển Dugong Lacépède, 1799",
        "tax_genus_latin": "Dugong Lacépède, 1799",
        "vn_size": "Chiều dài cơ thể trưởng thành 2,4 - 3,0 m; khối lượng trung bình 250 - 400 kg (cực đại tới 500 kg).",
        "vn_distribution": "Việt Nam: Hiện nay chỉ còn ghi nhận quần thể sinh sống tự nhiên tại vùng biển Vườn Quốc gia Côn Đảo (Bà Rịa - Vũng Tàu) và vùng biển Phú Quốc (Kiên Giang). Dẫn liệu lịch sử trước đây từng ghi nhận ở Vịnh Hạ Long, Cát Bà và vùng biển ven bờ Khánh Hòa.",
        "vn_specimen": "Bảo tàng Viện Hải dương học; Vườn Quốc gia Côn Đảo; Vườn Quốc gia Phú Quốc; các Lăng thờ Cá Ông duyên hải miền Trung (Đà Nẵng, Cù Lao Chàm).",
        "vn_status": "Sách Đỏ Việt Nam (2007): CR; Danh lục Đỏ VAST (2023): CR (Cực kỳ nguy cấp - Mã MM121); IUCN Red List: VU; Phụ lục I CITES; Nghị định 64/2019/NĐ-CP (Nhóm ưu tiên bảo vệ đặc biệt).",
        "vn_literature": "Đặng Huy Phương, 2023. Dugong dugon. Danh lục Đỏ Việt Nam (VAST); Smith et al., 1995. Marine mammals of Vietnam: a preliminary checklist. Collection of Marine Research Works 6: 147–176. NXB Khoa học và Kỹ thuật; McGowen et al., 2021. Whale temples are unique repositories for understanding marine mammal diversity in Central Vietnam. Raffles Bull Zool 69: 481–496.",
        "en_size": "Total length 2.4 - 3.0 m; body weight 250 - 400 kg (up to 500 kg).",
        "en_distribution": "Indo-West Pacific. In Vietnam: Surviving populations restricted to Con Dao Archipelago and Phu Quoc Island. Historically recorded in Ha Long Bay and Khanh Hoa.",
        "en_specimen": "Institute of Oceanography; Con Dao National Park; Whale temples in Da Nang and Cham Islands.",
        "en_status": "Vietnam Red Data Book: CR; VAST Red List (2023): CR; IUCN Red List: VU; CITES Appendix I; Decree 64/2019/ND-CP.",
        "en_literature": "Dang Huy Phuong, 2023; Smith et al., 1995; McGowen et al., 2021.",
        "conservation_status": "rare",
        "synonyms": json.dumps(["Trichechus dugon Müller, 1776", "Dugong australis Owen, 1847"]),
        "morphology_vn": "Thân hình con thoi thuôn dài, da dày nhẵn màu xám tro hoặc nâu xám ở lưng, bụng nhạt hơn. Đầu tròn, miệng mở chúc xuống phía dưới với môi trên rất dày và nhiều lông cảm giác cứng giúp bứt cỏ biển. Chi trước biến đổi thành vây bơi hình mái chèo dẹp, không có móng guốc; không có chi sau. Vây đuôi nằm ngang phẳng, xẻ thùy hình bán nguyệt giống đuôi cá voi. Cá thể đực trưởng thành có một đôi răng nanh nhô ra ngoài.",
        "ecology_vn": "Môi trường sống: Các vịnh nông kín gió, bãi triều và eo biển nước ấm trong xanh (độ sâu 1 - 10 m) nơi có các thảm cỏ biển phát triển dày đặc. Thức ăn: Là loài thú biển duy nhất chuyên ăn thực vật, thức ăn chủ yếu là các loài cỏ biển thuộc các chi Halodule, Halophila, Enhalus. Tập tính: Sống đơn độc hoặc theo nhóm nhỏ mẹ - con; di chuyển chậm rãi, nhút nhát và lặn dưới nước từ 1 - 3 phút rồi ngoi lên thở. Sinh sản: Thành thục sinh dục muộn (9 - 10 tuổi), thời gian mang thai 13 - 14 tháng, mỗi lứa chỉ đẻ 1 con non.",
        "economic_value_vn": "Là biểu tượng bảo tồn biển quý giá nhất Việt Nam; đóng vai trò then chốt trong việc duy trì chuỗi thức ăn và sức khỏe các thảm cỏ biển nhiệt đới. Nghiêm cấm tuyệt đối mọi hành vi săn bắt, mua bán.",
    },

    # ── BỘ CÁ VOI (Cetartiodactyla / Cetacea) — PHÂN BỘ MYSTICETI (Cá voi tấm sừng hàm) ──
    {
        "id": "thubien-species-2",
        "collection_id": "thu-bien",
        "volume": 1,
        "species_index": 2,
        "vn_name": "Cá voi Bryde",
        "scientific_name": "Balaenoptera edeni",
        "authorship": "Anderson, 1878",
        "en_common_name": "Bryde's whale",
        "vn_alternate_names": "Cá voi Eden, Cá Ông voi",
        "tax_class_vn": "Lớp Thú (Động vật có vú)",
        "tax_class_latin": "Mammalia",
        "tax_order_vn": "Bộ Cá voi",
        "tax_order_latin": "Cetacea",
        "tax_family_vn": "Họ Cá voi lưng đen",
        "tax_family_latin": "Balaenopteridae",
        "tax_genus_vn": "Chi Cá voi Balaenoptera Lacépède, 1804",
        "tax_genus_latin": "Balaenoptera Lacépède, 1804",
        "vn_size": "Chiều dài thân 12 - 15 m; khối lượng trung bình 12.000 - 25.000 kg.",
        "vn_distribution": "Vùng biển ven bờ và ngoài khơi toàn dải bờ biển Việt Nam. Thường xuyên xuất hiện kiếm ăn bầy đàn tại vùng biển Đề Gi (Bình Định), Cô Tô, Cát Bà, Bình Thuận, Khánh Hòa, Côn Đảo và Kiên Giang.",
        "vn_specimen": "Bộ xương lưu giữ tại Lăng Vạn Thủy Tú (Phan Thiết), Lăng Ông Cần Giờ, Bảo tàng Viện Hải dương học, Đền thờ Cá Ông Đề Gi (Bình Định).",
        "vn_status": "Sách Đỏ Việt Nam: VU; IUCN Red List: LC; Phụ lục I CITES; Nghị định 64/2019/NĐ-CP.",
        "vn_literature": "Smith et al. 1995. Collection of Marine Research Works 6: 147–176. NXB Khoa học và Kỹ thuật; Trần Đình Nho et al., 2022. Tạp chí KH-CN Thủy sản 2/2022: 81–90; McGowen et al., 2021. Raffles Bull Zool 69: 481–496.",
        "en_size": "Length 12 - 15 m; weight 12,000 - 25,000 kg.",
        "en_distribution": "Tropical and warm temperate waters worldwide. In Vietnam: Frequently observed feeding along coastal waters from Quang Ninh to Kien Giang (De Gi, Cat Ba, Con Dao).",
        "en_specimen": "Van Thuy Tu Temple (Phan Thiet), Can Gio Whale Temple, Institute of Oceanography Museum.",
        "en_status": "Vietnam Red Data Book: VU; IUCN: LC; CITES Appendix I.",
        "en_literature": "Smith et al., 1995; Tran Dinh Nho et al., 2022; McGowen et al., 2021.",
        "conservation_status": "rare",
        "morphology_vn": "Thân hình thuôn dài thon nhỏ đặc trưng của nhóm rorqual. Đầu có 3 đường gờ dọc nổi rõ rệt trên đỉnh mõm (1 gờ chính ở giữa và 2 gờ phụ song song hai bên - đặc điểm phân loại then chốt phân biệt với các loài Balaenoptera khác). Hàm trên có 250 - 370 phiến sừng màu xám đen với lông bờm thô. Có 40 - 70 rãnh nếp gấp da chạy dọc từ dưới cằm kéo dài đến rốn.",
        "ecology_vn": "Môi trường sống: Nước biển ấm nhiệt đới (trên 20°C), sống ở cả vùng nước nông ven bờ lẫn vùng khơi. Thức ăn: Ăn lọc các đàn cá nhỏ (cá trích, cá cơm, cá nục) và giáp xác phù du. Tập tính săn mồi há miệng đớp thẳng đứng (lunge feeding) rất ngoạn mục. Không di cư xa về vùng cực như các loài cá voi khác.",
        "economic_value_vn": "Loài thú biển linh thiêng gắn liền sâu sắc với Tín ngưỡng thờ cúng Cá Ông của ngư dân duyên hải Việt Nam; có giá trị du lịch sinh thái ngắm cá voi tại Đề Gi (Bình Định). Bảo vệ nghiêm ngặt.",
    },
    {
        "id": "thubien-species-3",
        "collection_id": "thu-bien",
        "volume": 1,
        "species_index": 3,
        "vn_name": "Cá voi xanh",
        "scientific_name": "Balaenoptera musculus",
        "authorship": "(Linnaeus, 1758)",
        "en_common_name": "Blue whale",
        "vn_alternate_names": "Cá voi khổng lồ",
        "tax_class_vn": "Lớp Thú (Động vật có vú)",
        "tax_class_latin": "Mammalia",
        "tax_order_vn": "Bộ Cá voi",
        "tax_order_latin": "Cetacea",
        "tax_family_vn": "Họ Cá voi lưng đen",
        "tax_family_latin": "Balaenopteridae",
        "tax_genus_vn": "Chi Cá voi Balaenoptera Lacépède, 1804",
        "tax_genus_latin": "Balaenoptera Lacépède, 1804",
        "vn_size": "Động vật lớn nhất hành tinh: Chiều dài cơ thể đạt 24 - 30 m; khối lượng có thể vượt quá 150.000 - 180.000 kg (150 - 180 tấn).",
        "vn_distribution": "Việt Nam: Ghi nhận di cư qua vùng biển khơi miền Trung, quần đảo Hoàng Sa, Trường Sa và vùng biển Tây Nam Bộ (từng ghi nhận trôi dạt dạt vào bờ biển Bạc Liêu, Quảng Bình).",
        "vn_specimen": "Bộ xương tại Bảo tàng Viện Hải dương học; Đền thờ Cá Ông ven biển miền Trung.",
        "vn_status": "Sách Đỏ Việt Nam: CR; Danh lục Đỏ VAST: CR; IUCN Red List: EN (Nguy cấp toàn cầu); Phụ lục I CITES; Nghị định 64/2019/NĐ-CP.",
        "vn_literature": "Smith et al. 1995. Collection of Marine Research Works 6: 147–176. NXB Khoa học và Kỹ thuật; Gruvel, 1925; Trần Đình Nho et al., 2022.",
        "en_size": "Length 24 - 30 m; weight up to 150 - 180 tons.",
        "en_distribution": "Cosmopolitan in all major oceans. In Vietnam: Deep offshore waters of Central Vietnam, Paracel and Spratly Archipelagos.",
        "en_specimen": "Institute of Oceanography Museum; local whale temples in central Vietnam.",
        "en_status": "Vietnam Red Data Book: CR; IUCN: EN; CITES Appendix I.",
        "en_literature": "Smith et al., 1995; Gruvel, 1925; Tran Dinh Nho et al., 2022.",
        "conservation_status": "rare",
        "morphology_vn": "Thân hình thon dài khổng lồ dạng khí động học. Màu da xám xanh đốm hoa văn cẩm thạch nhạt; khi lặn dưới nước phản chiếu màu xanh lam ngọc lộng lẫy. Đầu rộng hình chữ U dẹp phẳng với một gờ nổi duy nhất ở giữa đỉnh đầu. Vây lưng rất nhỏ (khoảng 30 cm) nằm lùi sâu về phía sau 3/4 thân. Hàm trên mang 300 - 400 tấm sừng hàm màu đen tuyền.",
        "ecology_vn": "Sống ngoài đại dương khơi sâu, bơi lội với tốc độ 20 - 50 km/h khi cần thiết. Thức ăn: Gần như chuyên biệt hoàn toàn đối với các loài giáp xác nhuyễn thể (nhuyễn thể euphausiids / krill); mỗi ngày tiêu thụ 3 - 4 tấn thức ăn. Cột nước phun qua lỗ thở có thể cao tới 9 - 12 mét.",
        "economic_value_vn": "Giá trị bảo tồn sinh thái tối cao toàn cầu; biểu tượng vĩ đại của đại dương. Được bảo vệ tuyệt đối.",
    },
    {
        "id": "thubien-species-4",
        "collection_id": "thu-bien",
        "volume": 1,
        "species_index": 4,
        "vn_name": "Cá voi vây",
        "scientific_name": "Balaenoptera physalus",
        "authorship": "(Linnaeus, 1758)",
        "en_common_name": "Fin whale",
        "vn_alternate_names": "Cá voi lưng dài",
        "tax_class_vn": "Lớp Thú (Động vật có vú)",
        "tax_class_latin": "Mammalia",
        "tax_order_vn": "Bộ Cá voi",
        "tax_order_latin": "Cetacea",
        "tax_family_vn": "Họ Cá voi lưng đen",
        "tax_family_latin": "Balaenopteridae",
        "tax_genus_vn": "Chi Cá voi Balaenoptera Lacépède, 1804",
        "tax_genus_latin": "Balaenoptera Lacépède, 1804",
        "vn_size": "Chiều dài cơ thể 18 - 22 m; khối lượng trung bình 40.000 - 70.000 kg.",
        "vn_distribution": "Việt Nam: Vùng biển khơi Vịnh Bắc Bộ, vùng biển miền Trung và Nam Bộ.",
        "vn_specimen": "Bộ xương trưng bày tại Viện Hải dương học và một số Lăng Ông ven biển Quảng Ninh, Bình Thuận.",
        "vn_status": "Sách Đỏ Việt Nam: EN; IUCN Red List: VU; Phụ lục I CITES.",
        "vn_literature": "Smith et al. 1995. Collection of Marine Research Works 6: 147–176. NXB Khoa học và Kỹ thuật; McGowen et al., 2021.",
        "en_size": "Length 18 - 22 m; weight 40,000 - 70,000 kg.",
        "en_distribution": "Worldwide in temperate and tropical oceans. In Vietnam: Gulf of Tonkin, Central and Southern offshore waters.",
        "en_specimen": "Institute of Oceanography; Whale temples in Quang Ninh and Binh Thuan.",
        "en_status": "Vietnam Red Data Book: EN; IUCN: VU; CITES Appendix I.",
        "en_literature": "Smith et al., 1995; McGowen et al., 2021.",
        "conservation_status": "rare",
        "morphology_vn": "Loài động vật lớn thứ hai thế giới sau cá voi xanh. Thân hình rất thuôn nhọn mảnh mai, được mệnh danh là 'ngựa xám đại dương'. Điểm nhận dạng độc nhất: Hoa văn bất đối xứng ở vùng đầu (hàm dưới bên phải có màu trắng ngà trong khi hàm dưới bên trái có màu xám đen). Có 50 - 100 nếp gấp da vùng họng ngực kéo dài tới rốn.",
        "ecology_vn": "Sống ngoài khơi xa, có khả năng bơi tốc độ cao nhất trong các loài cá voi lớn (tới 37 - 45 km/h). Thức ăn: Các đàn cá nhỏ tầng nổi, mực và giáp xác phù du. Thường di chuyển đơn độc hoặc cặp đôi.",
        "economic_value_vn": "Có giá trị bảo tồn biển và nghiên cứu hải dương học quốc tế đặc biệt quan trọng.",
    },
    {
        "id": "thubien-species-5",
        "collection_id": "thu-bien",
        "volume": 1,
        "species_index": 5,
        "vn_name": "Cá voi Sei",
        "scientific_name": "Balaenoptera borealis",
        "authorship": "Lesson, 1828",
        "en_common_name": "Sei whale",
        "vn_alternate_names": "Cá voi vược",
        "tax_class_vn": "Lớp Thú (Động vật có vú)",
        "tax_class_latin": "Mammalia",
        "tax_order_vn": "Bộ Cá voi",
        "tax_order_latin": "Cetacea",
        "tax_family_vn": "Họ Cá voi lưng đen",
        "tax_family_latin": "Balaenopteridae",
        "tax_genus_vn": "Chi Cá voi Balaenoptera Lacépède, 1804",
        "tax_genus_latin": "Balaenoptera Lacépède, 1804",
        "vn_size": "Chiều dài cơ thể 14 - 18 m; khối lượng trung bình 20.000 - 30.000 kg.",
        "vn_distribution": "Việt Nam: Vùng biển ngoài khơi biển Đông, di cư qua vùng biển miền Trung và quần đảo Hoàng Sa - Trường Sa.",
        "vn_specimen": "Mẫu sọ và xương tại Bảo tàng Viện Hải dương học.",
        "vn_status": "Sách Đỏ Việt Nam: EN; IUCN Red List: EN; Phụ lục I CITES.",
        "vn_literature": "Smith et al. 1995. Collection of Marine Research Works 6: 147–176. NXB Khoa học và Kỹ thuật.",
        "en_size": "Length 14 - 18 m; weight 20,000 - 30,000 kg.",
        "en_distribution": "Deep offshore waters worldwide. In Vietnam: Offshore waters of South China Sea.",
        "en_specimen": "Institute of Oceanography Museum.",
        "en_status": "Vietnam Red Data Book: EN; IUCN: EN; CITES Appendix I.",
        "en_literature": "Smith et al., 1995.",
        "conservation_status": "rare",
        "morphology_vn": "Lưng màu xám đen bóng ánh thép với các đốm sẹo hình bầu dục nhạt màu do vết cắn của cá mập cookiecutter. Vây lưng cao hình lưỡi liềm (25 - 60 cm), nằm khoảng 2/3 thân. Mõm nhọn, trên đỉnh đầu chỉ có một gờ duy nhất. Phiến sừng hàm mang lông mịn mượt như lụa, thích nghi lọc giáp xác chân chèo nhỏ.",
        "ecology_vn": "Sống ngoài vùng biển khơi sâu, ưa vùng nước có nhiệt độ mát và ôn hòa. Kiếm ăn gần mặt nước bằng cách bơi lướt liên tục (skimming) để lọc giáp xác chân chèo (copepods) và nhuyễn thể.",
        "economic_value_vn": "Loài thú biển nguy cấp toàn cầu, cần được bảo vệ vùng di cư sinh thái.",
    },
    {
        "id": "thubien-species-6",
        "collection_id": "thu-bien",
        "volume": 1,
        "species_index": 6,
        "vn_name": "Cá voi Minke thông thường",
        "scientific_name": "Balaenoptera acutorostrata",
        "authorship": "Lacépède, 1804",
        "en_common_name": "Common minke whale",
        "vn_alternate_names": "Cá voi nhỏ",
        "tax_class_vn": "Lớp Thú (Động vật có vú)",
        "tax_class_latin": "Mammalia",
        "tax_order_vn": "Bộ Cá voi",
        "tax_order_latin": "Cetacea",
        "tax_family_vn": "Họ Cá voi lưng đen",
        "tax_family_latin": "Balaenopteridae",
        "tax_genus_vn": "Chi Cá voi Balaenoptera Lacépède, 1804",
        "tax_genus_latin": "Balaenoptera Lacépède, 1804",
        "vn_size": "Chiều dài cơ thể 7 - 9 m; khối lượng khoảng 5.000 - 8.000 kg.",
        "vn_distribution": "Việt Nam: Ghi nhận tại vùng biển Vịnh Bắc Bộ (Bạch Long Vĩ, Hải Phòng), vùng biển Trung Bộ và Nam Bộ.",
        "vn_specimen": "Mẫu vật tại Bảo tàng Lịch sử Hải Phòng, Viện Hải dương học.",
        "vn_status": "IUCN Red List: LC; Phụ lục I CITES; Nghị định 64/2019/NĐ-CP.",
        "vn_literature": "Smith et al. 1995. Collection of Marine Research Works 6: 147–176. NXB Khoa học và Kỹ thuật; Trần Đình Nho et al., 2022.",
        "en_size": "Length 7 - 9 m; weight 5,000 - 8,000 kg.",
        "en_distribution": "Widespread across oceans. In Vietnam: Gulf of Tonkin, Central and Southern coastal waters.",
        "en_specimen": "Hai Phong Museum; Institute of Oceanography.",
        "en_status": "IUCN: LC; CITES Appendix I.",
        "en_literature": "Smith et al., 1995; Tran Dinh Nho et al., 2022.",
        "conservation_status": "rare",
        "morphology_vn": "Loài nhỏ nhất trong chi Balaenoptera. Thân hình thuôn mập; đầu hình tam giác nhọn hoắt đặc trưng. Lưng xám đen sẫm, bụng trắng. Vây ngực có một dải băng màu trắng sáng vắt ngang rất rõ rệt (đặc điểm nhận dạng then chốt ở phân loài Bắc bán cầu). Vây lưng cao hình liềm cong về phía sau.",
        "ecology_vn": "Thường bơi vào vùng nước ven bờ, vùng vịnh và cửa sông kín gió. Tính tò mò, hay tiếp cận tàu thuyền. Thức ăn là các loài cá nhỏ sống bầy đàn và giáp xác.",
        "economic_value_vn": "Giá trị sinh thái và bảo tồn nguồn lợi biển.",
    },
    {
        "id": "thubien-species-7",
        "collection_id": "thu-bien",
        "volume": 1,
        "species_index": 7,
        "vn_name": "Cá voi Omura",
        "scientific_name": "Balaenoptera omurai",
        "authorship": "Wada, Oishi & Yamada, 2003",
        "en_common_name": "Omura's whale",
        "vn_alternate_names": "Cá voi lùn Omura",
        "tax_class_vn": "Lớp Thú (Động vật có vú)",
        "tax_class_latin": "Mammalia",
        "tax_order_vn": "Bộ Cá voi",
        "tax_order_latin": "Cetacea",
        "tax_family_vn": "Họ Cá voi lưng đen",
        "tax_family_latin": "Balaenopteridae",
        "tax_genus_vn": "Chi Cá voi Balaenoptera Lacépède, 1804",
        "tax_genus_latin": "Balaenoptera Lacépède, 1804",
        "vn_size": "Chiều dài cơ thể 10 - 12 m; khối lượng khoảng 8.000 - 14.000 kg.",
        "vn_distribution": "Việt Nam: Đã phát hiện và giám định thành công các mẫu sọ lịch sử tại Đền thờ Cá Ông ở Đà Nẵng, Quảng Ngãi và vùng biển miền Trung.",
        "vn_specimen": "Hai hộp sọ bảo quản tại Lăng Ông Đà Nẵng (mẫu DN2019-T4) và Bảo tàng Viện Hải dương học.",
        "vn_status": "IUCN Red List: DD (Thiếu dữ liệu); Phụ lục I CITES.",
        "vn_literature": "McGowen, Vu Long et al., 2021. Whale temples are unique repositories for understanding marine mammal diversity in Central Vietnam. Raffles Bull Zool 69: 481–496; Wada et al., 2003.",
        "en_size": "Length 10 - 12 m; weight 8,000 - 14,000 kg.",
        "en_distribution": "Indo-Pacific tropical and subtropical waters. In Vietnam: Confirmed from whale temple skulls in Da Nang and Quang Ngai.",
        "en_specimen": "Whale temples in Da Nang and Quang Ngai; Institute of Oceanography.",
        "en_status": "IUCN: DD; CITES Appendix I.",
        "en_literature": "McGowen et al., 2021; Wada et al., 2003.",
        "conservation_status": "rare",
        "morphology_vn": "Mới được khoa học quốc tế mô tả vào năm 2003. Hình thái ngoài rất giống cá voi Bryde và cá voi vây nhưng nhỏ hơn; hộp sọ có đặc điểm xương đỉnh trùm lên bờ trên mỏm ổ mắt xương trán và có 2 lỗ nhỏ tại đường khớp giữa xương đỉnh và xương vảy. Hoa văn màu sắc bất đối xứng ở họng ngực tương tự cá voi vây.",
        "ecology_vn": "Sống ở vùng biển ấm nhiệt đới, sinh sống quanh năm ở vùng nước ấm mà không thực hiện các cuộc di cư dài ngày về vùng cực. Ăn các đàn sinh vật phù du và giáp xác nhỏ.",
        "economic_value_vn": "Phát hiện có giá trị khoa học to lớn, khẳng định vị thế độc đáo của các Lăng Cá Ông Việt Nam như kho lưu trữ tài nguyên đa dạng sinh học biển thế giới.",
    },
    {
        "id": "thubien-species-8",
        "collection_id": "thu-bien",
        "volume": 1,
        "species_index": 8,
        "vn_name": "Cá voi lưng gù",
        "scientific_name": "Megaptera novaeangliae",
        "authorship": "(Borowski, 1781)",
        "en_common_name": "Humpback whale",
        "vn_alternate_names": "Cá voi bướu",
        "tax_class_vn": "Lớp Thú (Động vật có vú)",
        "tax_class_latin": "Mammalia",
        "tax_order_vn": "Bộ Cá voi",
        "tax_order_latin": "Cetacea",
        "tax_family_vn": "Họ Cá voi lưng đen",
        "tax_family_latin": "Balaenopteridae",
        "tax_genus_vn": "Chi Cá voi lưng gù Megaptera Gray, 1846",
        "tax_genus_latin": "Megaptera Gray, 1846",
        "vn_size": "Chiều dài cơ thể 13 - 16 m; khối lượng trung bình 25.000 - 35.000 kg.",
        "vn_distribution": "Việt Nam: Di cư qua vùng biển miền Trung, vùng biển Nha Trang, Ninh Thuận, Bình Thuận và Vịnh Bắc Bộ (Bạch Long Vĩ).",
        "vn_specimen": "Bộ xương tại Lăng Tân Vạn (Đảo Lý Sơn, Quảng Ngãi), Viện Hải dương học, Bảo tàng Đồ Sơn (Hải Phòng).",
        "vn_status": "Sách Đỏ Việt Nam: VU; IUCN Red List: LC; Phụ lục I CITES; Nghị định 64/2019/NĐ-CP.",
        "vn_literature": "Smith et al. 1995. Collection of Marine Research Works 6: 147–176. NXB Khoa học và Kỹ thuật; McGowen et al., 2021; Trần Đình Nho et al., 2022.",
        "en_size": "Length 13 - 16 m; weight 25,000 - 35,000 kg.",
        "en_distribution": "Worldwide in all major oceans. In Vietnam: Migrates along Central Vietnam, Ly Son Island, Khanh Hoa, Bach Long Vi.",
        "en_specimen": "Ly Son Whale Temple, Institute of Oceanography Museum.",
        "en_status": "Vietnam Red Data Book: VU; IUCN: LC; CITES Appendix I.",
        "en_literature": "Smith et al., 1995; McGowen et al., 2021.",
        "conservation_status": "rare",
        "morphology_vn": "Thân mập chắc, lưng hơi cong gù khi lặn. Điểm đặc trưng nhất là đôi vây ngực cực kỳ dài (chiếm tới 1/3 chiều dài thân), mép vây lượn sóng gồ ghề dạng răng cưa. Đầu và hàm dưới phủ nhiều nốt u tròn lồi (tubercles), trên mỗi u có một sợi lông cảm giác. Mặt dưới thùy đuôi có hoa văn đen trắng độc bản như dấu vân tay của từng cá thể.",
        "ecology_vn": "Nổi tiếng với tập tính nhào lộn vọt lên khỏi mặt nước (breaching) và dùng vây ngực đập mặt nước. Nổi tiếng với 'bài ca cá voi' phức tạp của con đực trong mùa sinh sản. Có tập tính săn mồi bằng lưới bong bóng khí (bubble-net feeding) độc đáo.",
        "economic_value_vn": "Có ý nghĩa tâm linh to lớn với ngư dân miền biển; giá trị biểu tượng sinh thái đại dương toàn cầu.",
    },
    {
        "id": "thubien-species-9",
        "collection_id": "thu-bien",
        "volume": 1,
        "species_index": 9,
        "vn_name": "Cá voi xám",
        "scientific_name": "Eschrichtius robustus",
        "authorship": "(Lilljeborg, 1861)",
        "en_common_name": "Gray whale",
        "vn_alternate_names": "Cá voi tro",
        "tax_class_vn": "Lớp Thú (Động vật có vú)",
        "tax_class_latin": "Mammalia",
        "tax_order_vn": "Bộ Cá voi",
        "tax_order_latin": "Cetacea",
        "tax_family_vn": "Họ Cá voi xám",
        "tax_family_latin": "Eschrichtiidae",
        "tax_genus_vn": "Chi Eschrichtius Gray, 1864",
        "tax_genus_latin": "Eschrichtius Gray, 1864",
        "vn_size": "Chiều dài cơ thể 13 - 15 m; khối lượng khoảng 25.000 - 35.000 kg.",
        "vn_distribution": "Việt Nam: Ghi nhận mẫu vật tại vùng biển Quảng Ninh - Vịnh Bắc Bộ (mẫu vật bộ xương bảo quản tại Bảo tàng Lịch sử Quảng Ninh).",
        "vn_specimen": "Bộ xương dài 14m tại Bảo tàng Lịch sử tỉnh Quảng Ninh (mẫu BQN01).",
        "vn_status": "IUCN Red List: LC (quần thể Tây Thái Bình Dương: CR - Cực kỳ nguy cấp); Phụ lục I CITES.",
        "vn_literature": "Đặng Ngọc Thanh et al., Báo cáo Thú biển Vịnh Bắc Bộ; Bảo tàng Lịch sử Quảng Ninh; IUCN Cetacean Specialist Group.",
        "en_size": "Length 13 - 15 m; weight 25,000 - 35,000 kg.",
        "en_distribution": "North Pacific Ocean. In Vietnam: Confirmed from an intact skeleton specimen from Quang Ninh coastal waters.",
        "en_specimen": "Quang Ninh Provincial Museum (14m specimen BQN01).",
        "en_status": "IUCN: LC (Western North Pacific subpopulation: CR); CITES Appendix I.",
        "en_literature": "Quang Ninh Museum records; IUCN Cetacean Specialist Group.",
        "conservation_status": "rare",
        "morphology_vn": "Thân màu xám tro lốm đốm nhiều mảng trắng xám do các đám hà biển và rận cá voi bám ký sinh. Không có vây lưng thật sự, thay vào đó là một gờ thấp ở lưng sau đó là một chuỗi 6 - 12 gờ nhỏ gập ghềnh kéo dài tới đuôi. Hàm trên mang khoảng 130 - 180 phiến sừng ngắn dày màu vàng nhạt.",
        "ecology_vn": "Là loài cá voi tấm sừng duy nhất chuyên sục sạo kiếm ăn dưới đáy biển (benthic feeder). Chúng bơi nghiêng một bên thân sát đáy biển, hút bùn cát và lọc các loài giáp xác lưỡng thê (amphipods) sống vùi trong đáy mềm.",
        "economic_value_vn": "Mẫu vật lịch sử vô cùng quý hiếm mở rộng vùng phân bố khoa học của quần thể cá voi xám Tây Thái Bình Dương xuống phía nam.",
    },

    # ── BỘ CÁ VOI (Cetartiodactyla / Cetacea) — PHÂN BỘ ODONTOCETI (Cá voi có răng) ──
    # Họ Cá nhà táng (Physeteridae)
    {
        "id": "thubien-species-10",
        "collection_id": "thu-bien",
        "volume": 1,
        "species_index": 10,
        "vn_name": "Cá nhà táng",
        "scientific_name": "Physeter macrocephalus",
        "authorship": "Linnaeus, 1758",
        "en_common_name": "Sperm whale",
        "vn_alternate_names": "Cá voi đầu vuông, Cá voi răng lớn",
        "tax_class_vn": "Lớp Thú (Động vật có vú)",
        "tax_class_latin": "Mammalia",
        "tax_order_vn": "Bộ Cá voi",
        "tax_order_latin": "Cetacea",
        "tax_family_vn": "Họ Cá nhà táng",
        "tax_family_latin": "Physeteridae",
        "tax_genus_vn": "Chi Cá nhà táng Physeter Linnaeus, 1758",
        "tax_genus_latin": "Physeter Linnaeus, 1758",
        "vn_size": "Loài cá voi có răng lớn nhất: Chiều dài con đực đạt 16 - 20 m (khối lượng 40.000 - 55.000 kg); con cái dài 11 - 13 m (khối lượng 15.000 - 20.000 kg).",
        "vn_distribution": "Việt Nam: Vùng biển khơi sâu thềm lục địa miền Trung, rãnh nước sâu quần đảo Hoàng Sa, Trường Sa và vùng biển Phú Yên, Bình Thuận, Côn Đảo.",
        "vn_specimen": "Bộ xương và mẫu răng tại Viện Hải dương học; Đền thờ Cá Ông Tuy Hòa (Phú Yên) và Lăng Vạn Thủy Tú (Phan Thiết).",
        "vn_status": "Sách Đỏ Việt Nam: VU; Danh lục Đỏ VAST: VU; IUCN Red List: VU; Phụ lục I CITES; Nghị định 64/2019/NĐ-CP.",
        "vn_literature": "Smith et al. 1995. Collection of Marine Research Works 6: 147–176. NXB Khoa học và Kỹ thuật; Trần Đình Nho et al., 2022; McGowen et al., 2021.",
        "en_size": "Males 16 - 20 m (40 - 55 tons); females 11 - 13 m (15 - 20 tons).",
        "en_distribution": "Worldwide in deep oceanic waters. In Vietnam: Continental shelf drop-offs of Central Vietnam, Paracel and Spratly Islands.",
        "en_specimen": "Institute of Oceanography; Whale temples in Phu Yen and Binh Thuan.",
        "en_status": "Vietnam Red Data Book: VU; IUCN: VU; CITES Appendix I.",
        "en_literature": "Smith et al., 1995; Tran Dinh Nho et al., 2022; McGowen et al., 2021.",
        "conservation_status": "rare",
        "morphology_vn": "Đầu hình khối hộp vuông vức khổng lồ chiếm tới 1/3 chiều dài cơ thể; bên trong chứa khoang dầu tinh tinh (spermaceti) đặc trưng. Lỗ thở nằm lệch hẳn sang phía bên trái ở chóp mõm, khi phun nước tạo cột hơi nghiêng góc 45 độ về phía trước. Hàm dưới hẹp và mang 20 - 26 đôi răng hình nón sắc nhọn gắn chặt vào các hố thụt ở hàm trên.",
        "ecology_vn": "Bậc thầy lặn sâu của thế giới động vật: có thể lặn sâu tới 1.000 - 2.500 m và nín thở hơn 90 phút dưới đáy đại dương tối tăm. Thức ăn chủ yếu là các loài mực ống khổng lồ (Architeuthis) và cá đáy khơi sâu.",
        "economic_value_vn": "Có ý nghĩa khoa học và bảo tồn hải dương học vô giá. Trong lịch sử từng cung cấp long diên hương (ambergris) quý giá. Được tôn kính bậc nhất tại các đền thờ Cá Ông miền Trung.",
    },

    # Họ Cá nhà táng nhỏ & lùn (Kogiidae)
    {
        "id": "thubien-species-11",
        "collection_id": "thu-bien",
        "volume": 1,
        "species_index": 11,
        "vn_name": "Cá nhà táng nhỏ",
        "scientific_name": "Kogia breviceps",
        "authorship": "(de Blainville, 1838)",
        "en_common_name": "Pygmy sperm whale",
        "vn_alternate_names": "Cá Ông chuông nhỏ",
        "tax_class_vn": "Lớp Thú (Động vật có vú)",
        "tax_class_latin": "Mammalia",
        "tax_order_vn": "Bộ Cá voi",
        "tax_order_latin": "Cetacea",
        "tax_family_vn": "Họ Cá nhà táng nhỏ",
        "tax_family_latin": "Kogiidae",
        "tax_genus_vn": "Chi Kogia Gray, 1846",
        "tax_genus_latin": "Kogia Gray, 1846",
        "vn_size": "Chiều dài cơ thể 3,0 - 3,5 m; khối lượng khoảng 300 - 450 kg.",
        "vn_distribution": "Việt Nam: Vùng biển Quảng Ngãi, Khánh Hòa, Bình Thuận, Bạc Liêu, Trà Vinh.",
        "vn_specimen": "Mẫu vật lịch sử được Serène ghi nhận tại Viện Hải dương học từ năm 1934; các mẫu vật mắc cạn tại Bạc Liêu, Trà Vinh.",
        "vn_status": "IUCN Red List: LC; Phụ lục II CITES.",
        "vn_literature": "Serène, 1934; Smith et al. 1995. Collection of Marine Research Works 6: 147–176. NXB Khoa học và Kỹ thuật; Trần Đình Nho et al., 2022.",
        "en_size": "Length 3.0 - 3.5 m; weight 300 - 450 kg.",
        "en_distribution": "Tropical and temperate waters. In Vietnam: Central and Southern coastal waters (Quang Ngai, Khanh Hoa, Bac Lieu).",
        "en_specimen": "Institute of Oceanography (first reported by Serene 1934); local temples.",
        "en_status": "IUCN: LC; CITES Appendix II.",
        "en_literature": "Serene, 1934; Smith et al., 1995; Tran Dinh Nho et al., 2022.",
        "conservation_status": "rare",
        "morphology_vn": "Đầu tù tròn dạng khối hộp nhỏ, hàm dưới nhỏ và thụt vào bên dưới mõm tương tự cá mập. Phía sau mắt có một vệt sáng hình lưỡi liềm trông như khe mang giả của cá mập. Hàm dưới có 12 - 16 đôi răng cong nhọn như kim; hàm trên thường không có răng. Vây lưng nhỏ hình móc câu nằm sau giữa lưng.",
        "ecology_vn": "Sống ngoài thềm lục địa sâu, bơi lội chậm rãi nổi lững lờ trên mặt nước khi nghỉ ngơi. Khi hoảng sợ có cơ chế xả ra một đám dịch màu nâu đỏ từ túi ruột để làm mù kẻ thù (giống mực phun mực) rồi lặn biến mất.",
        "economic_value_vn": "Loài thú biển hiếm gặp, có giá trị nghiên cứu sinh thái học hành vi độc đáo.",
    },
    {
        "id": "thubien-species-12",
        "collection_id": "thu-bien",
        "volume": 1,
        "species_index": 12,
        "vn_name": "Cá nhà táng lùn",
        "scientific_name": "Kogia sima",
        "authorship": "(Owen, 1866)",
        "en_common_name": "Dwarf sperm whale",
        "vn_alternate_names": "Cá Ông chuông lùn",
        "tax_class_vn": "Lớp Thú (Động vật có vú)",
        "tax_class_latin": "Mammalia",
        "tax_order_vn": "Bộ Cá voi",
        "tax_order_latin": "Cetacea",
        "tax_family_vn": "Họ Cá nhà táng nhỏ",
        "tax_family_latin": "Kogiidae",
        "tax_genus_vn": "Chi Kogia Gray, 1846",
        "tax_genus_latin": "Kogia Gray, 1846",
        "vn_size": "Chiều dài cơ thể 2,1 - 2,7 m; khối lượng khoảng 150 - 250 kg.",
        "vn_distribution": "Việt Nam: Vùng biển ngoài khơi miền Trung và Nam Bộ.",
        "vn_specimen": "Lưu giữ tại các đền thờ Cá Ông ven biển miền Trung.",
        "vn_status": "IUCN Red List: LC; Phụ lục II CITES.",
        "vn_literature": "Smith et al. 1995. Collection of Marine Research Works 6: 147–176. NXB Khoa học và Kỹ thuật; McGowen et al., 2021.",
        "en_size": "Length 2.1 - 2.7 m; weight 150 - 250 kg.",
        "en_distribution": "Tropical and subtropical oceans. In Vietnam: Central and Southern offshore regions.",
        "en_specimen": "Whale temples in Central Vietnam; Institute of Oceanography.",
        "en_status": "IUCN: LC; CITES Appendix II.",
        "en_literature": "Smith et al., 1995; McGowen et al., 2021.",
        "conservation_status": "rare",
        "morphology_vn": "Rất giống cá nhà táng nhỏ Kogia breviceps nhưng kích thước bé hơn và vây lưng cao hơn, nằm ở khoảng giữa lưng. Mõm ngắn và vuông vức hơn. Hàm dưới mang 7 - 12 đôi răng sắc nhọn, đôi khi có tới 3 đôi răng nhỏ ở hàm trên.",
        "ecology_vn": "Sống ở vùng thềm dốc lục địa sâu, kiếm ăn các loài mực ống, cá tầng đáy và cua biển. Thường bơi chậm, lặng lẽ và khó phát hiện trên mặt biển.",
        "economic_value_vn": "Có giá trị nghiên cứu sinh thái biển sâu.",
    },

    # Họ Cá voi có mỏ (Ziphiidae)
    {
        "id": "thubien-species-13",
        "collection_id": "thu-bien",
        "volume": 1,
        "species_index": 13,
        "vn_name": "Cá voi có mỏ Cuvier",
        "scientific_name": "Ziphius cavirostris",
        "authorship": "Cuvier, 1823",
        "en_common_name": "Cuvier's beaked whale",
        "vn_alternate_names": "Cá voi mõm khoằm Cuvier",
        "tax_class_vn": "Lớp Thú (Động vật có vú)",
        "tax_class_latin": "Mammalia",
        "tax_order_vn": "Bộ Cá voi",
        "tax_order_latin": "Cetacea",
        "tax_family_vn": "Họ Cá voi có mỏ",
        "tax_family_latin": "Ziphiidae",
        "tax_genus_vn": "Chi Ziphius G. Cuvier, 1823",
        "tax_genus_latin": "Ziphius G. Cuvier, 1823",
        "vn_size": "Chiều dài cơ thể 5,5 - 7,0 m; khối lượng khoảng 2.500 - 3.500 kg.",
        "vn_distribution": "Việt Nam: Vùng biển miền Trung (ghi nhận mẫu vật tại Khánh Hòa, Ninh Thuận, Bình Thuận).",
        "vn_specimen": "Hộp sọ lưu giữ tại Bảo tàng Viện Hải dương học; mẫu vật ghi nhận mắc cạn tại Bình Thuận.",
        "vn_status": "IUCN Red List: LC; Phụ lục II CITES.",
        "vn_literature": "Smith et al. 1995. Collection of Marine Research Works 6: 147–176. NXB Khoa học và Kỹ thuật; Trần Đình Nho et al., 2022.",
        "en_size": "Length 5.5 - 7.0 m; weight 2,500 - 3,500 kg.",
        "en_distribution": "Deep pelagic waters globally. In Vietnam: Offshore waters of Khanh Hoa, Ninh Thuan, Binh Thuan.",
        "en_specimen": "Institute of Oceanography Museum; stranding records in Binh Thuan.",
        "en_status": "IUCN: LC; CITES Appendix II.",
        "en_literature": "Smith et al., 1995; Tran Dinh Nho et al., 2022.",
        "conservation_status": "rare",
        "morphology_vn": "Thân hình con thoi mập mạp. Đầu dốc thoai thoải không có nếp gấp trán rõ rệt; mỏ ngắn và cùn. Miệng cong hình chữ S với nụ cười đặc trưng. Con đực trưởng thành có 1 đôi răng nanh hình nón nhô ra ngoài ở chóp hàm dưới. Lưng xám nâu hoặc vàng nâu, thân phủ nhiều vết sẹo tròn nhạt màu.",
        "ecology_vn": "Nắm giữ kỷ lục động vật có vú lặn sâu và lâu nhất thế giới: độ sâu ghi nhận lên tới gần 3.000 m và nín thở tới 222 phút. Thức ăn chuyên biệt là mực tầng đáy đại dương.",
        "economic_value_vn": "Giá trị sinh học và nghiên cứu sinh lý học lặn sâu đặc biệt quý giá.",
    },
    {
        "id": "thubien-species-14",
        "collection_id": "thu-bien",
        "volume": 1,
        "species_index": 14,
        "vn_name": "Cá voi có mỏ Blainville",
        "scientific_name": "Mesoplodon densirostris",
        "authorship": "(de Blainville, 1817)",
        "en_common_name": "Blainville's beaked whale",
        "vn_alternate_names": "Cá voi mõm khoằm Blainville",
        "tax_class_vn": "Lớp Thú (Động vật có vú)",
        "tax_class_latin": "Mammalia",
        "tax_order_vn": "Bộ Cá voi",
        "tax_order_latin": "Cetacea",
        "tax_family_vn": "Họ Cá voi có mỏ",
        "tax_family_latin": "Ziphiidae",
        "tax_genus_vn": "Chi Mesoplodon Gervais, 1850",
        "tax_genus_latin": "Mesoplodon Gervais, 1850",
        "vn_size": "Chiều dài cơ thể 4,5 - 5,0 m; khối lượng khoảng 800 - 1.000 kg.",
        "vn_distribution": "Việt Nam: Vùng biển khơi sâu miền Trung và quần đảo Hoàng Sa - Trường Sa.",
        "vn_specimen": "Mẫu vật hộp sọ tại Viện Hải dương học.",
        "vn_status": "IUCN Red List: LC; Phụ lục II CITES.",
        "vn_literature": "Smith et al. 1995. Collection of Marine Research Works 6: 147–176. NXB Khoa học và Kỹ thuật.",
        "en_size": "Length 4.5 - 5.0 m; weight 800 - 1,000 kg.",
        "en_distribution": "Deep waters worldwide. In Vietnam: South China Sea offshore.",
        "en_specimen": "Institute of Oceanography.",
        "en_status": "IUCN: LC; CITES Appendix II.",
        "en_literature": "Smith et al., 1995.",
        "conservation_status": "rare",
        "morphology_vn": "Hàm dưới có cấu trúc vòm cong gồ cao lên rất đặc biệt ở giữa hàm; ở con đực, trên đỉnh vòm cong này có 2 chiếc răng nanh khổng lồ mọc hướng thẳng lên trời nhô cao qua hàm trên.",
        "ecology_vn": "Sống ngoài rãnh biển sâu đại dương, lặn sâu từ 800 - 1.500 m để săn mực ống và cá tầng đáy.",
        "economic_value_vn": "Bảo tồn nguồn lợi thú biển sâu.",
    },
    {
        "id": "thubien-species-15",
        "collection_id": "thu-bien",
        "volume": 1,
        "species_index": 15,
        "vn_name": "Cá voi có mỏ răng bạch quả",
        "scientific_name": "Mesoplodon ginkgodens",
        "authorship": "Nishiwaki & Kamiya, 1958",
        "en_common_name": "Ginkgo-toothed beaked whale",
        "vn_alternate_names": "Cá voi mõm khoằm răng bạch quả",
        "tax_class_vn": "Lớp Thú (Động vật có vú)",
        "tax_class_latin": "Mammalia",
        "tax_order_vn": "Bộ Cá voi",
        "tax_order_latin": "Cetacea",
        "tax_family_vn": "Họ Cá voi có mỏ",
        "tax_family_latin": "Ziphiidae",
        "tax_genus_vn": "Chi Mesoplodon Gervais, 1850",
        "tax_genus_latin": "Mesoplodon Gervais, 1850",
        "vn_size": "Chiều dài cơ thể 4,8 - 5,3 m; khối lượng khoảng 1.200 - 1.500 kg.",
        "vn_distribution": "Việt Nam: Vùng biển nhiệt đới Biển Đông và ngoài khơi Trung Bộ.",
        "vn_specimen": "Mẫu vật hộp sọ giám định tại Viện Hải dương học.",
        "vn_status": "IUCN Red List: DD; Phụ lục II CITES.",
        "vn_literature": "Smith et al. 1995. Collection of Marine Research Works 6: 147–176. NXB Khoa học và Kỹ thuật; Nishiwaki & Kamiya, 1958.",
        "en_size": "Length 4.8 - 5.3 m; weight 1,200 - 1,500 kg.",
        "en_distribution": "Indo-Pacific deep pelagic waters. In Vietnam: South China Sea.",
        "en_specimen": "Institute of Oceanography.",
        "en_status": "IUCN: DD; CITES Appendix II.",
        "en_literature": "Smith et al., 1995.",
        "conservation_status": "rare",
        "morphology_vn": "Răng của con đực có hình dạng dẹt xòe rộng rất giống hình chiếc lá cây bạch quả (Ginkgo biloba). Mõm thon dài vừa phải, màu sắc toàn thân xám sẫm đồng nhất.",
        "ecology_vn": "Là một trong những loài cá voi có mỏ bí ẩn và ít được bắt gặp nhất trên thế giới. Chuyên ăn mực ở tầng nước sâu.",
        "economic_value_vn": "Có giá trị khoa học cao trong phân loại học thú biển thế giới.",
    },
    {
        "id": "thubien-species-16",
        "collection_id": "thu-bien",
        "volume": 1,
        "species_index": 16,
        "vn_name": "Cá voi có mỏ Longman",
        "scientific_name": "Indopacetus pacificus",
        "authorship": "(Longman, 1926)",
        "en_common_name": "Longman's beaked whale",
        "vn_alternate_names": "Cá voi mõm khoằm nhiệt đới",
        "tax_class_vn": "Lớp Thú (Động vật có vú)",
        "tax_class_latin": "Mammalia",
        "tax_order_vn": "Bộ Cá voi",
        "tax_order_latin": "Cetacea",
        "tax_family_vn": "Họ Cá voi có mỏ",
        "tax_family_latin": "Ziphiidae",
        "tax_genus_vn": "Chi Indopacetus Moore, 1968",
        "tax_genus_latin": "Indopacetus Moore, 1968",
        "vn_size": "Chiều dài cơ thể 6,0 - 6,5 m; khối lượng khoảng 2.000 - 3.000 kg.",
        "vn_distribution": "Việt Nam: Vùng biển ngoài khơi sâu Biển Đông và Trường Sa.",
        "vn_specimen": "Mẫu vật sọ lưu giữ tại Bảo tàng Viện Hải dương học.",
        "vn_status": "IUCN Red List: LC; Phụ lục II CITES.",
        "vn_literature": "Smith et al. 1995. Collection of Marine Research Works 6: 147–176. NXB Khoa học và Kỹ thuật; Dalebout et al., 2003.",
        "en_size": "Length 6.0 - 6.5 m; weight 2,000 - 3,000 kg.",
        "en_distribution": "Tropical Indo-Pacific. In Vietnam: Deep pelagic waters of South China Sea.",
        "en_specimen": "Institute of Oceanography.",
        "en_status": "IUCN: LC; CITES Appendix II.",
        "en_literature": "Smith et al., 1995; Dalebout et al., 2003.",
        "conservation_status": "rare",
        "morphology_vn": "Kích thước lớn trong họ Ziphiidae. Mõm dài rõ rệt, trán hơi tròn dốc. Vây lưng tương đối lớn hình tam giác hơi móc câu. Vùng đầu và cổ của con trưởng thành thường có màu sáng nhạt hơn thân.",
        "ecology_vn": "Sống theo nhóm đàn nhỏ từ 10 - 20 cá thể ở vùng nước sâu trên 1.000 mét. Săn bắt mực ống tầng khơi sâu.",
        "economic_value_vn": "Ghi nhận sự hiện diện quý hiếm của hệ động vật biển sâu tại Việt Nam.",
    },

    # Họ Cá heo chuột (Phocoenidae)
    {
        "id": "thubien-species-17",
        "collection_id": "thu-bien",
        "volume": 1,
        "species_index": 17,
        "vn_name": "Cá heo không vây Ấn Độ Dương",
        "scientific_name": "Neophocaena phocaenoides",
        "authorship": "(G. Cuvier, 1829)",
        "en_common_name": "Indo-Pacific finless porpoise",
        "vn_alternate_names": "Cá nược không vây, Cá nược chuột, Cá Ông sư",
        "tax_class_vn": "Lớp Thú (Động vật có vú)",
        "tax_class_latin": "Mammalia",
        "tax_order_vn": "Bộ Cá voi",
        "tax_order_latin": "Cetacea",
        "tax_family_vn": "Họ Cá heo chuột",
        "tax_family_latin": "Phocoenidae",
        "tax_genus_vn": "Chi Neophocaena Palmer, 1899",
        "tax_genus_latin": "Neophocaena Palmer, 1899",
        "vn_size": "Chiều dài cơ thể 1,4 - 1,7 m; khối lượng khoảng 30 - 45 kg.",
        "vn_distribution": "Phổ biến dọc toàn bộ bờ biển Việt Nam từ Quảng Ninh, Hải Phòng (Cát Bà, Bái Tử Long), Thừa Thiên Huế, Đà Nẵng, Quảng Nam, Quảng Ngãi, Bình Định, Khánh Hòa tới Kiên Giang.",
        "vn_specimen": "Chiếm số lượng mẫu vật hộp sọ lớn nhất tại các Đền thờ Cá Ông miền Trung (41/140 mẫu trong nghiên cứu McGowen et al. 2021); Bảo tàng Viện Hải dương học; VQG Bái Tử Long.",
        "vn_status": "Sách Đỏ Việt Nam: VU; IUCN Red List: VU (Sắp nguy cấp); Phụ lục I CITES; Nghị định 64/2019/NĐ-CP.",
        "vn_literature": "Smith et al. 1995. Collection of Marine Research Works 6: 147–176. NXB Khoa học và Kỹ thuật; McGowen et al., 2021. Raffles Bull Zool 69: 481–496.",
        "en_size": "Length 1.4 - 1.7 m; weight 30 - 45 kg.",
        "en_distribution": "Coastal waters of Indo-Pacific. In Vietnam: Most common small cetacean, abundant along entire coast (Quang Ninh, Da Nang, Khanh Hoa, Kien Giang).",
        "en_specimen": "Most abundant species in Vietnamese whale temples (>41 skulls examined); Institute of Oceanography.",
        "en_status": "Vietnam Red Data Book: VU; IUCN: VU; CITES Appendix I; Decree 64/2019/ND-CP.",
        "en_literature": "Smith et al., 1995; McGowen et al., 2021.",
        "conservation_status": "rare",
        "morphology_vn": "Không có vây lưng hoàn toàn (thay vào đó là một gờ thấp chạy dọc sống lưng mang nhiều hàng nốt sần hạt nhỏ). Đầu tròn vo, trán dốc đứng, hoàn toàn không có mỏ. Răng dẹp hình chiếc xẻng (spade-shaped) đặc trưng của họ Cá heo chuột, khác hẳn răng hình nón của họ cá heo mỏ. Toàn thân màu xám chì hoặc xám nhạt, bụng sáng màu hơn.",
        "ecology_vn": "Sinh sống ở vùng nước nông ven bờ (dưới 50m nước), vùng cửa sông, rừng ngập mặn và quanh các đảo ven bờ. Thức ăn: Cá nhỏ ven bờ, tôm và mực ống. Sống đơn độc hoặc theo nhóm nhỏ 2 - 5 cá thể.",
        "economic_value_vn": "Loài thú biển ven bờ gắn bó mật thiết nhất với ngư dân; hiện đang chịu sức ép rất lớn từ lưới cước đánh cá và tàu thuyền ven bờ.",
    },
    {
        "id": "thubien-species-18",
        "collection_id": "thu-bien",
        "volume": 1,
        "species_index": 18,
        "vn_name": "Cá heo không vây Đông Á",
        "scientific_name": "Neophocaena asiaeorientalis",
        "authorship": "(Pilleri & Gihr, 1972)",
        "en_common_name": "Narrow-ridged finless porpoise",
        "vn_alternate_names": "Cá nược gờ hẹp",
        "tax_class_vn": "Lớp Thú (Động vật có vú)",
        "tax_class_latin": "Mammalia",
        "tax_order_vn": "Bộ Cá voi",
        "tax_order_latin": "Cetacea",
        "tax_family_vn": "Họ Cá heo chuột",
        "tax_family_latin": "Phocoenidae",
        "tax_genus_vn": "Chi Neophocaena Palmer, 1899",
        "tax_genus_latin": "Neophocaena Palmer, 1899",
        "vn_size": "Chiều dài cơ thể 1,5 - 1,8 m; khối lượng khoảng 35 - 50 kg.",
        "vn_distribution": "Việt Nam: Ghi nhận ở vùng biển Vịnh Bắc Bộ (vùng biển ven bờ Quảng Ninh, Hải Phòng giáp với vùng phân bố phía bắc).",
        "vn_specimen": "Mẫu sọ thu thập tại vùng Vịnh Bắc Bộ và VQG Bái Tử Long.",
        "vn_status": "IUCN Red List: EN (Nguy cấp); Phụ lục I CITES.",
        "vn_literature": "Jefferson & Wang, 2011; Đặng Ngọc Thanh et al.; Smith et al., 1999.",
        "en_size": "Length 1.5 - 1.8 m; weight 35 - 50 kg.",
        "en_distribution": "Coastal waters of East Asia. In Vietnam: Northern Gulf of Tonkin (Quang Ninh).",
        "en_specimen": "Bai Tu Long National Park; Gulf of Tonkin surveys.",
        "en_status": "IUCN: EN; CITES Appendix I.",
        "en_literature": "Jefferson & Wang, 2011; Smith et al., 1999.",
        "conservation_status": "rare",
        "morphology_vn": "Tương tự Neophocaena phocaenoides nhưng dải gờ hạt trên lưng hẹp hơn rõ rệt (rộng dưới 12 mm so với gờ rộng trên 15 - 20 mm của loài Ấn Độ Dương) và vị trí bắt đầu gờ hạt nằm lùi sâu hơn về phía sau thân.",
        "ecology_vn": "Sống ven bờ biển và vùng cửa sông nước lợ. Thức ăn là cá nhỏ và giáp xác.",
        "economic_value_vn": "Bảo tồn nguồn gien thú biển quý hiếm vùng Vịnh Bắc Bộ.",
    },

    # Họ Cá heo mỏ (Delphinidae)
    {
        "id": "thubien-species-19",
        "collection_id": "thu-bien",
        "volume": 1,
        "species_index": 19,
        "vn_name": "Cá heo trắng Trung Hoa",
        "scientific_name": "Sousa chinensis",
        "authorship": "(Osbeck, 1765)",
        "en_common_name": "Indo-Pacific humpback dolphin",
        "vn_alternate_names": "Cá heo hồng, Cá heo lưng bướu Thái Bình Dương",
        "tax_class_vn": "Lớp Thú (Động vật có vú)",
        "tax_class_latin": "Mammalia",
        "tax_order_vn": "Bộ Cá voi",
        "tax_order_latin": "Cetacea",
        "tax_family_vn": "Họ Cá heo mỏ",
        "tax_family_latin": "Delphinidae",
        "tax_genus_vn": "Chi Cá heo lưng bướu Sousa Gray, 1866",
        "tax_genus_latin": "Sousa Gray, 1866",
        "vn_size": "Chiều dài cơ thể 2,2 - 2,8 m; khối lượng khoảng 150 - 230 kg.",
        "vn_distribution": "Việt Nam: Quần thể cư trú nổi tiếng tại Vịnh Hạ Long, Vịnh Bái Tử Long (Quảng Ninh), Vồ Đầm, cửa sông Văn Úc (Hải Phòng), Đồ Sơn, cửa sông Thu Bồn (Quảng Nam), Đà Nẵng và vùng biển Kiên Giang.",
        "vn_specimen": "Mẫu vật hộp sọ phổ biến tại các Đền thờ Cá Ông Đà Nẵng, Hội An, Huế; Bảo tàng VQG Bái Tử Long; Viện Hải dương học.",
        "vn_status": "Sách Đỏ Việt Nam: CR; Danh lục Đỏ VAST: CR; IUCN Red List: VU; Phụ lục I CITES; Nghị định 64/2019/NĐ-CP.",
        "vn_literature": "Smith et al. 1995. Collection of Marine Research Works 6: 147–176. NXB Khoa học và Kỹ thuật; McGowen et al., 2021. Raffles Bull Zool 69: 481–496; Jefferson et al., 2017.",
        "en_size": "Length 2.2 - 2.8 m; weight 150 - 230 kg.",
        "en_distribution": "Coastal waters of Indo-Pacific. In Vietnam: Established resident populations in Ha Long Bay, Bai Tu Long, Do Son, Da Nang, Hoi An, Kien Giang.",
        "en_specimen": "Whale temples in Da Nang, Hoi An, Hue; Bai Tu Long NP; Institute of Oceanography.",
        "en_status": "Vietnam Red Data Book: CR; IUCN: VU; CITES Appendix I; Decree 64/2019/ND-CP.",
        "en_literature": "Smith et al., 1995; McGowen et al., 2021; Jefferson et al., 2017.",
        "conservation_status": "rare",
        "morphology_vn": "Điểm kỳ thú nhất là sự đổi màu theo lứa tuổi: Con non mới sinh có màu xám chì đậm, khi lớn dần chuyển sang màu xám đốm hồng, và cá thể trưởng thành hoàn toàn có màu trắng ngà ánh hồng phấn lộng lẫy. Mỏ thon dài rõ rệt, vây lưng mọc trên một bướu thịt thấp rộng ở giữa lưng.",
        "ecology_vn": "Chỉ sinh sống ở vùng nước nông ven bờ (thường dưới 20m nước), gần các cửa sông lớn, đầm phá và rừng ngập mặn. Thức ăn là các loài cá tầng đáy và cá cửa sông (cá đối, cá đù, cá phèn). Rất thân thiện với con người.",
        "economic_value_vn": "Biểu tượng du lịch sinh thái và bảo tồn đa dạng sinh học biển nổi bật tại Vịnh Hạ Long và Bái Tử Long. Nghiêm cấm khai thác.",
    },
    {
        "id": "thubien-species-20",
        "collection_id": "thu-bien",
        "volume": 1,
        "species_index": 20,
        "vn_name": "Cá heo Irrawaddy",
        "scientific_name": "Orcaella brevirostris",
        "authorship": "(Owen in Gray, 1866)",
        "en_common_name": "Irrawaddy dolphin",
        "vn_alternate_names": "Cá nược, Cá nược Minh Hải",
        "tax_class_vn": "Lớp Thú (Động vật có vú)",
        "tax_class_latin": "Mammalia",
        "tax_order_vn": "Bộ Cá voi",
        "tax_order_latin": "Cetacea",
        "tax_family_vn": "Họ Cá heo mỏ",
        "tax_family_latin": "Delphinidae",
        "tax_genus_vn": "Chi Orcaella Gray, 1866",
        "tax_genus_latin": "Orcaella Gray, 1866",
        "vn_size": "Chiều dài cơ thể 2,0 - 2,4 m; khối lượng khoảng 90 - 130 kg.",
        "vn_distribution": "Việt Nam: Hiện nay chủ yếu ghi nhận tại vùng biển Tây Nam Bộ (Khu dự trữ sinh quyển Kiên Giang, vùng biển Hà Tiên, Phú Quốc). Trước đây từng phân bố sâu vào hệ thống sông Cửu Long (sông Tiền, sông Hậu) nhưng hiện tại đã biến mất ở vùng sông.",
        "vn_specimen": "Mẫu vật lịch sử tại Viện Hải dương học; Đền thờ Cá Ông vùng Kiên Giang, Bạc Liêu, Cà Mau.",
        "vn_status": "Sách Đỏ Việt Nam: CR; Danh lục Đỏ VAST: CR; IUCN Red List: EN (Nguy cấp toàn cầu); Phụ lục I CITES; Nghị định 64/2019/NĐ-CP.",
        "vn_literature": "Lloze, 1973; Baird et al., 1994; Smith et al., 1995; Vũ Long (CBES), 2017-2022. Rufford Foundation Conservation Report.",
        "en_size": "Length 2.0 - 2.4 m; weight 90 - 130 kg.",
        "en_distribution": "Coastal and riverine waters of Southeast Asia. In Vietnam: Kien Giang Biosphere Reserve, Phu Quoc, Ha Tien; historically in Mekong Delta.",
        "en_specimen": "Institute of Oceanography; local temples in Southwest Vietnam.",
        "en_status": "Vietnam Red Data Book: CR; IUCN: EN; CITES Appendix I; Decree 64/2019/ND-CP.",
        "en_literature": "Lloze, 1973; Baird et al., 1994; Smith et al., 1995; Vu Long, 2017.",
        "conservation_status": "rare",
        "morphology_vn": "Đầu tròn vo, trán nhô gồ cao hình bán cầu, hoàn toàn không có mỏ dài. Khác với cá heo không vây, cá heo Irrawaddy có một vây lưng nhỏ hình tam giác tù nằm ở khoảng 2/3 thân. Cổ rất linh hoạt có nếp gấp rõ rệt. Toàn thân màu xám xanh đồng nhất, mặt bụng nhạt hơn.",
        "ecology_vn": "Ưa thích vùng nước lợ cửa sông, vịnh biển cạn và rừng ngập mặn. Thức ăn: Cá nhỏ, giáp xác và mực. Có tập tính phun vòi nước thành tia từ miệng độc đáo để lùa cá.",
        "economic_value_vn": "Đang đứng trước nguy cơ tuyệt chủng rất cao tại Việt Nam do suy thoái môi trường cửa sông và mắc lưới cước đánh cá.",
    },
    {
        "id": "thubien-species-21",
        "collection_id": "thu-bien",
        "volume": 1,
        "species_index": 21,
        "vn_name": "Cá heo mũi chai Ấn Độ Dương",
        "scientific_name": "Tursiops aduncus",
        "authorship": "(Ehrenberg, 1833)",
        "en_common_name": "Indo-Pacific bottlenose dolphin",
        "vn_alternate_names": "Cá heo mũi chai đốm",
        "tax_class_vn": "Lớp Thú (Động vật có vú)",
        "tax_class_latin": "Mammalia",
        "tax_order_vn": "Bộ Cá voi",
        "tax_order_latin": "Cetacea",
        "tax_family_vn": "Họ Cá heo mỏ",
        "tax_family_latin": "Delphinidae",
        "tax_genus_vn": "Chi Cá heo mũi chai Tursiops Gervais, 1855",
        "tax_genus_latin": "Tursiops Gervais, 1855",
        "vn_size": "Chiều dài cơ thể 2,2 - 2,6 m; khối lượng khoảng 150 - 230 kg.",
        "vn_distribution": "Việt Nam: Phổ biến ở vùng ven bờ và quanh các đảo từ Bắc vào Nam (Vịnh Bắc Bộ, Cù Lao Chàm, Nha Trang, Côn Đảo, Phú Quốc).",
        "vn_specimen": "Chiếm số lượng lớn trong các bộ sọ cá heo tại Đền thờ Cá Ông Đà Nẵng, Cù Lao Chàm, Hội An; Viện Hải dương học.",
        "vn_status": "IUCN Red List: NT (Gần bị đe dọa); Phụ lục II CITES.",
        "vn_literature": "Smith et al. 1995. Collection of Marine Research Works 6: 147–176. NXB Khoa học và Kỹ thuật; McGowen et al., 2021. Raffles Bull Zool 69: 481–496.",
        "en_size": "Length 2.2 - 2.6 m; weight 150 - 230 kg.",
        "en_distribution": "Indo-Pacific coastal waters. In Vietnam: Very common along coast and islands (Cham Islands, Nha Trang, Con Dao, Phu Quoc).",
        "en_specimen": "Numerous skulls in whale temples of Central Vietnam; Institute of Oceanography.",
        "en_status": "IUCN: NT; CITES Appendix II.",
        "en_literature": "Smith et al., 1995; McGowen et al., 2021.",
        "conservation_status": "rare",
        "morphology_vn": "Mỏ thon dài vừa phải hình chai rõ rệt, rãnh phân cách mỏ và trán sâu. Cơ thể thon gọn hơn loài Tursiops truncatus. Khi trưởng thành, mặt bụng xuất hiện nhiều đốm đen nhỏ đặc trưng.",
        "ecology_vn": "Sống theo bầy đàn từ 5 - 15 cá thể ở vùng rạn san hô, bãi đá ven bờ và vịnh biển kín. Thông minh, hoạt bát, hay nhào lộn theo sóng mũi tàu thuyền.",
        "economic_value_vn": "Loài cá heo thông minh quen thuộc, giá trị du lịch sinh thái biển.",
    },
    {
        "id": "thubien-species-22",
        "collection_id": "thu-bien",
        "volume": 1,
        "species_index": 22,
        "vn_name": "Cá heo mũi chai thông thường",
        "scientific_name": "Tursiops truncatus",
        "authorship": "(Montagu, 1821)",
        "en_common_name": "Common bottlenose dolphin",
        "vn_alternate_names": "Cá heo mũi chai đại dương",
        "tax_class_vn": "Lớp Thú (Động vật có vú)",
        "tax_class_latin": "Mammalia",
        "tax_order_vn": "Bộ Cá voi",
        "tax_order_latin": "Cetacea",
        "tax_family_vn": "Họ Cá heo mỏ",
        "tax_family_latin": "Delphinidae",
        "tax_genus_vn": "Chi Cá heo mũi chai Tursiops Gervais, 1855",
        "tax_genus_latin": "Tursiops Gervais, 1855",
        "vn_size": "Chiều dài cơ thể 2,7 - 3,8 m; khối lượng khoảng 250 - 450 kg.",
        "vn_distribution": "Việt Nam: Vùng biển khơi xa và thềm lục địa toàn dải biển Đông.",
        "vn_specimen": "Mẫu sọ tại Đền thờ Cá Ông Cù Lao Chàm, Đà Nẵng; Bảo tàng Viện Hải dương học.",
        "vn_status": "IUCN Red List: LC; Phụ lục II CITES.",
        "vn_literature": "Smith et al. 1995. Collection of Marine Research Works 6: 147–176. NXB Khoa học và Kỹ thuật; McGowen et al., 2021.",
        "en_size": "Length 2.7 - 3.8 m; weight 250 - 450 kg.",
        "en_distribution": "Pelagic and coastal worldwide. In Vietnam: Offshore waters of South China Sea.",
        "en_specimen": "Cham Islands whale temples; Institute of Oceanography.",
        "en_status": "IUCN: LC; CITES Appendix II.",
        "en_literature": "Smith et al., 1995; McGowen et al., 2021.",
        "conservation_status": "rare",
        "morphology_vn": "Cơ thể to lớn lực lưỡng hơn T. aduncus. Mỏ ngắn hơn và chắc chắn, bụng màu trắng kem sạch sẽ không có đốm đen khi trưởng thành. Vây lưng cao hình lưỡi liềm cong.",
        "ecology_vn": "Sống bầy đàn ngoài biển khơi, bơi lội khỏe, săn cá nổi và mực ống.",
        "economic_value_vn": "Bảo vệ sinh thái đại dương.",
    },
    {
        "id": "thubien-species-23",
        "collection_id": "thu-bien",
        "volume": 1,
        "species_index": 23,
        "vn_name": "Cá heo đốm nhiệt đới",
        "scientific_name": "Stenella attenuata",
        "authorship": "(Nasmyth, 1835)",
        "en_common_name": "Pantropical spotted dolphin",
        "vn_alternate_names": "Cá heo đốm",
        "tax_class_vn": "Lớp Thú (Động vật có vú)",
        "tax_class_latin": "Mammalia",
        "tax_order_vn": "Bộ Cá voi",
        "tax_order_latin": "Cetacea",
        "tax_family_vn": "Họ Cá heo mỏ",
        "tax_family_latin": "Delphinidae",
        "tax_genus_vn": "Chi Stenella Gray, 1866",
        "tax_genus_latin": "Stenella Gray, 1866",
        "vn_size": "Chiều dài cơ thể 1,8 - 2,3 m; khối lượng khoảng 90 - 120 kg.",
        "vn_distribution": "Việt Nam: Rất phổ biến ở vùng biển ngoài khơi miền Trung, quần đảo Hoàng Sa, Trường Sa và Vịnh Bắc Bộ.",
        "vn_specimen": "Nhiều mẫu vật hộp sọ tại các Đền thờ Cá Ông Hội An, Đà Nẵng, Lý Sơn; Viện Hải dương học.",
        "vn_status": "IUCN Red List: LC; Phụ lục II CITES.",
        "vn_literature": "Smith et al. 1995. Collection of Marine Research Works 6: 147–176. NXB Khoa học và Kỹ thuật; McGowen et al., 2021.",
        "en_size": "Length 1.8 - 2.3 m; weight 90 - 120 kg.",
        "en_distribution": "Tropical oceans worldwide. In Vietnam: Common offshore Central Vietnam, Paracel and Spratly Islands.",
        "en_specimen": "Hoi An, Da Nang, Ly Son whale temples; Institute of Oceanography.",
        "en_status": "IUCN: LC; CITES Appendix II.",
        "en_literature": "Smith et al., 1995; McGowen et al., 2021.",
        "conservation_status": "rare",
        "morphology_vn": "Thân thon dài duyên dáng. Mỏ dài và hẹp, chóp mỏ có màu trắng sáng. Toàn thân phủ vô số đốm hoa văn lấm chấm: lưng phủ đốm trắng nhạt trên nền da sẫm, còn bụng phủ đốm sẫm trên nền da sáng. Vây lưng cao mảnh mai hình liềm.",
        "ecology_vn": "Sống theo những đàn lớn từ hàng chục đến hàng trăm cá thể ở vùng nước khơi sâu. Thường bơi cùng các đàn cá ngừ đại dương (tuna) và cá heo spinner. Nhào lộn rất giỏi.",
        "economic_value_vn": "Chỉ thị quan trọng cho ngư trường cá ngừ đại dương miền Trung.",
    },
    {
        "id": "thubien-species-24",
        "collection_id": "thu-bien",
        "volume": 1,
        "species_index": 24,
        "vn_name": "Cá heo spinner",
        "scientific_name": "Stenella longirostris",
        "authorship": "(Gray, 1828)",
        "en_common_name": "Spinner dolphin",
        "vn_alternate_names": "Cá heo mỏ dài, Cá heo xoay",
        "tax_class_vn": "Lớp Thú (Động vật có vú)",
        "tax_class_latin": "Mammalia",
        "tax_order_vn": "Bộ Cá voi",
        "tax_order_latin": "Cetacea",
        "tax_family_vn": "Họ Cá heo mỏ",
        "tax_family_latin": "Delphinidae",
        "tax_genus_vn": "Chi Stenella Gray, 1866",
        "tax_genus_latin": "Stenella Gray, 1866",
        "vn_size": "Chiều dài cơ thể 1,7 - 2,1 m; khối lượng khoảng 60 - 80 kg.",
        "vn_distribution": "Việt Nam: Vùng biển ngoài khơi miền Trung, vùng biển quanh các hải đảo Cù Lao Chàm, Lý Sơn, Côn Đảo, Phú Quốc.",
        "vn_specimen": "Mẫu vật hộp sọ tại Đền thờ Cá Ông Hội An; Viện Hải dương học.",
        "vn_status": "IUCN Red List: LC; Phụ lục II CITES.",
        "vn_literature": "Smith et al. 1995. Collection of Marine Research Works 6: 147–176. NXB Khoa học và Kỹ thuật; McGowen et al., 2021.",
        "en_size": "Length 1.7 - 2.1 m; weight 60 - 80 kg.",
        "en_distribution": "Tropical pelagic oceans. In Vietnam: Offshore waters and islands (Cham Islands, Con Dao).",
        "en_specimen": "Hoi An whale temple; Institute of Oceanography.",
        "en_status": "IUCN: LC; CITES Appendix II.",
        "en_literature": "Smith et al., 1995; McGowen et al., 2021.",
        "conservation_status": "rare",
        "morphology_vn": "Mỏ đặc biệt dài và thon mảnh; màu da chia thành 3 dải màu rõ rệt: sống lưng xám đen sẫm, hai bên sườn xám nhạt và bụng trắng hồng. Vây lưng hình tam giác hơi dựng đứng.",
        "ecology_vn": "Nổi tiếng nhất đại dương với tập tính phóng thẳng lên không trung và xoay tròn cơ thể 4 - 7 vòng quanh trục thân trước khi rơi xuống nước. Kiếm ăn đêm ở vùng nước sâu các loài cá nhỏ và mực phát quang.",
        "economic_value_vn": "Giá trị giải trí, du lịch sinh thái ngắm cá heo nhào lộn trên biển.",
    },
    {
        "id": "thubien-species-25",
        "collection_id": "thu-bien",
        "volume": 1,
        "species_index": 25,
        "vn_name": "Cá heo sọc",
        "scientific_name": "Stenella coeruleoalba",
        "authorship": "(Meyen, 1833)",
        "en_common_name": "Striped dolphin",
        "vn_alternate_names": "Cá heo vằn xanh",
        "tax_class_vn": "Lớp Thú (Động vật có vú)",
        "tax_class_latin": "Mammalia",
        "tax_order_vn": "Bộ Cá voi",
        "tax_order_latin": "Cetacea",
        "tax_family_vn": "Họ Cá heo mỏ",
        "tax_family_latin": "Delphinidae",
        "tax_genus_vn": "Chi Stenella Gray, 1866",
        "tax_genus_latin": "Stenella Gray, 1866",
        "vn_size": "Chiều dài cơ thể 2,0 - 2,5 m; khối lượng khoảng 100 - 150 kg.",
        "vn_distribution": "Việt Nam: Vùng biển ngoài khơi sâu Trung Bộ và vùng biển Hoàng Sa, Trường Sa.",
        "vn_specimen": "Hộp sọ lưu giữ tại Đền thờ Cá Ông Đà Nẵng, Quảng Nam; Viện Hải dương học.",
        "vn_status": "IUCN Red List: LC; Phụ lục II CITES.",
        "vn_literature": "Smith et al. 1995. Collection of Marine Research Works 6: 147–176. NXB Khoa học và Kỹ thuật; McGowen et al., 2021.",
        "en_size": "Length 2.0 - 2.5 m; weight 100 - 150 kg.",
        "en_distribution": "Temperate and tropical pelagic waters. In Vietnam: Offshore deep waters of Central Vietnam.",
        "en_specimen": "Da Nang and Quang Nam whale temples; Institute of Oceanography.",
        "en_status": "IUCN: LC; CITES Appendix II.",
        "en_literature": "Smith et al., 1995; McGowen et al., 2021.",
        "conservation_status": "rare",
        "morphology_vn": "Nhận diện bằng các dải sọc màu xanh đen uốn lượn chạy dọc hai bên thân: một dải sọc chạy từ mắt về gốc vây ngực và một dải sọc khác kéo dài từ mắt uốn lượn dọc thân về phía rốn. Lưng màu xanh dương sẫm ánh kim.",
        "ecology_vn": "Bơi lội rất nhanh nhẹn, có tập tính nhảy vọt lướt sóng cao trên mặt biển (roto-tailing). Săn các loài mực và cá nổi tầng trung đại dương.",
        "economic_value_vn": "Bảo tồn sinh vật biển khơi.",
    },
    {
        "id": "thubien-species-26",
        "collection_id": "thu-bien",
        "volume": 1,
        "species_index": 26,
        "vn_name": "Cá heo răng nhám",
        "scientific_name": "Steno bredanensis",
        "authorship": "(G. Cuvier in Lesson, 1828)",
        "en_common_name": "Rough-toothed dolphin",
        "vn_alternate_names": "Cá heo mõm thon",
        "tax_class_vn": "Lớp Thú (Động vật có vú)",
        "tax_class_latin": "Mammalia",
        "tax_order_vn": "Bộ Cá voi",
        "tax_order_latin": "Cetacea",
        "tax_family_vn": "Họ Cá heo mỏ",
        "tax_family_latin": "Delphinidae",
        "tax_genus_vn": "Chi Steno Gray, 1846",
        "tax_genus_latin": "Steno Gray, 1846",
        "vn_size": "Chiều dài cơ thể 2,1 - 2,6 m; khối lượng khoảng 100 - 155 kg.",
        "vn_distribution": "Việt Nam: Vùng biển ngoài khơi miền Trung (Quảng Nam, Bình Định, Khánh Hòa).",
        "vn_specimen": "Mẫu vật hộp sọ tại các Đền thờ Cá Ông miền Trung; Viện Hải dương học.",
        "vn_status": "IUCN Red List: LC; Phụ lục II CITES.",
        "vn_literature": "Smith et al. 1995. Collection of Marine Research Works 6: 147–176. NXB Khoa học và Kỹ thuật; McGowen et al., 2021.",
        "en_size": "Length 2.1 - 2.6 m; weight 100 - 155 kg.",
        "en_distribution": "Deep tropical oceans. In Vietnam: Offshore waters of Central Vietnam.",
        "en_specimen": "Central Vietnam whale temples; Institute of Oceanography.",
        "en_status": "IUCN: LC; CITES Appendix II.",
        "en_literature": "Smith et al., 1995; McGowen et al., 2021.",
        "conservation_status": "rare",
        "morphology_vn": "Đầu có hình nón vuốt dài độc đáo: trán dốc đều mượt mà xuống mỏ mà hoàn toàn không có rãnh gấp phân cách như các loài cá heo khác. Môi và cằm có màu trắng hồng. Men răng có nhiều đường gờ nhám gồ ghề đặc trưng.",
        "ecology_vn": "Sống ngoài vùng biển sâu, lặn nín thở tới 15 phút. Thức ăn: Cá nục heo (mahi-mahi), mực nang và cá tầng đáy.",
        "economic_value_vn": "Nghiên cứu hình thái học so sánh tiến hóa thú biển.",
    },
    {
        "id": "thubien-species-27",
        "collection_id": "thu-bien",
        "volume": 1,
        "species_index": 27,
        "vn_name": "Cá heo Risso",
        "scientific_name": "Grampus griseus",
        "authorship": "(G. Cuvier, 1812)",
        "en_common_name": "Risso's dolphin",
        "vn_alternate_names": "Cá heo xám, Cá heo đầu tròn rãnh",
        "tax_class_vn": "Lớp Thú (Động vật có vú)",
        "tax_class_latin": "Mammalia",
        "tax_order_vn": "Bộ Cá voi",
        "tax_order_latin": "Cetacea",
        "tax_family_vn": "Họ Cá heo mỏ",
        "tax_family_latin": "Delphinidae",
        "tax_genus_vn": "Chi Grampus Gray, 1828",
        "tax_genus_latin": "Grampus Gray, 1828",
        "vn_size": "Chiều dài cơ thể 3,0 - 3,8 m; khối lượng khoảng 300 - 500 kg.",
        "vn_distribution": "Việt Nam: Vùng biển ngoài khơi thềm dốc miền Trung (Đà Nẵng, Quảng Nam, Quảng Ngãi, Bình Thuận).",
        "vn_specimen": "Mẫu sọ lưu giữ tại Đền thờ Cá Ông Đà Nẵng (mẫu DN2019-T4-008); Viện Hải dương học.",
        "vn_status": "IUCN Red List: LC; Phụ lục II CITES.",
        "vn_literature": "Smith et al. 1995. Collection of Marine Research Works 6: 147–176. NXB Khoa học và Kỹ thuật; McGowen et al., 2021. Raffles Bull Zool 69: 481–496.",
        "en_size": "Length 3.0 - 3.8 m; weight 300 - 500 kg.",
        "en_distribution": "Worldwide in deep temperate and tropical waters. In Vietnam: Central offshore shelf.",
        "en_specimen": "Da Nang whale temple (DN2019-T4-008); Institute of Oceanography.",
        "en_status": "IUCN: LC; CITES Appendix II.",
        "en_literature": "Smith et al., 1995; McGowen et al., 2021.",
        "conservation_status": "rare",
        "morphology_vn": "Thân trước rất mập mạp và thon dần về phía đuôi. Đầu tròn to dạng khối vuông, hoàn toàn không có mỏ; chính giữa trán có một rãnh xẻ dọc đặc trưng hình chữ V. Toàn thân phủ chằng chịt các vết sẹo trắng ngoằn ngoèo (do răng của đồng loại và xúc tu mực tạo thành khi giằng co). Hàm trên không có răng; hàm dưới chỉ có 2 - 7 đôi răng ở chóp hàm.",
        "ecology_vn": "Sống ngoài thềm dốc lục địa sâu (độ sâu 400 - 1.000m). Chuyên săn bắt các loài mực đại dương vào ban đêm.",
        "economic_value_vn": "Đặc trưng sinh thái vùng dốc thềm lục địa sâu miền Trung.",
    },
    {
        "id": "thubien-species-28",
        "collection_id": "thu-bien",
        "volume": 1,
        "species_index": 28,
        "vn_name": "Cá heo Fraser",
        "scientific_name": "Lagenodelphis hosei",
        "authorship": "Fraser, 1956",
        "en_common_name": "Fraser's dolphin",
        "vn_alternate_names": "Cá heo Sarawak",
        "tax_class_vn": "Lớp Thú (Động vật có vú)",
        "tax_class_latin": "Mammalia",
        "tax_order_vn": "Bộ Cá voi",
        "tax_order_latin": "Cetacea",
        "tax_family_vn": "Họ Cá heo mỏ",
        "tax_family_latin": "Delphinidae",
        "tax_genus_vn": "Chi Lagenodelphis Fraser, 1956",
        "tax_genus_latin": "Lagenodelphis Fraser, 1956",
        "vn_size": "Chiều dài cơ thể 2,3 - 2,7 m; khối lượng khoảng 160 - 210 kg.",
        "vn_distribution": "Việt Nam: Vùng biển ngoài khơi sâu miền Trung (Đà Nẵng, Quảng Nam, Quảng Ngãi).",
        "vn_specimen": "Mẫu sọ lưu giữ tại Đền thờ Cá Ông Hội An (mẫu HA2019-T4); Viện Hải dương học.",
        "vn_status": "IUCN Red List: LC; Phụ lục II CITES.",
        "vn_literature": "Smith et al. 1995. Collection of Marine Research Works 6: 147–176. NXB Khoa học và Kỹ thuật; McGowen et al., 2021.",
        "en_size": "Length 2.3 - 2.7 m; weight 160 - 210 kg.",
        "en_distribution": "Deep tropical waters worldwide. In Vietnam: Central deep offshore.",
        "en_specimen": "Hoi An whale temple (HA2019-T4); Institute of Oceanography.",
        "en_status": "IUCN: LC; CITES Appendix II.",
        "en_literature": "Smith et al., 1995; McGowen et al., 2021.",
        "conservation_status": "rare",
        "morphology_vn": "Thân hình mập chắc lực lưỡng. Vây ngực và vây lưng nhỏ khác thường so với kích thước thân thể. Mỏ cực kỳ ngắn nhưng rõ rệt. Có một dải sọc màu đen sẫm đặc trưng chạy từ mắt dọc theo lườn thân về phía hậu môn.",
        "ecology_vn": "Sống thành những đàn lớn từ 100 đến cả ngàn cá thể ngoài đại dương khơi sâu. Bơi lội rất mạnh mẽ, săn cá tầng đáy và mực.",
        "economic_value_vn": "Bảo tồn thú biển khơi.",
    },
    {
        "id": "thubien-species-29",
        "collection_id": "thu-bien",
        "volume": 1,
        "species_index": 29,
        "vn_name": "Cá voi đầu tròn vây ngắn",
        "scientific_name": "Globicephala macrorhynchus",
        "authorship": "Gray, 1846",
        "en_common_name": "Short-finned pilot whale",
        "vn_alternate_names": "Cá voi tiêu công, Cá Ông tiêu",
        "tax_class_vn": "Lớp Thú (Động vật có vú)",
        "tax_class_latin": "Mammalia",
        "tax_order_vn": "Bộ Cá voi",
        "tax_order_latin": "Cetacea",
        "tax_family_vn": "Họ Cá heo mỏ",
        "tax_family_latin": "Delphinidae",
        "tax_genus_vn": "Chi Globicephala Lesson, 1828",
        "tax_genus_latin": "Globicephala Lesson, 1828",
        "vn_size": "Chiều dài cơ thể 4,5 - 6,0 m; khối lượng khoảng 1.500 - 3.000 kg.",
        "vn_distribution": "Việt Nam: Vùng biển ngoài khơi sâu miền Trung (Đà Nẵng, Quảng Nam, Khánh Hòa, Bình Thuận).",
        "vn_specimen": "Mẫu sọ bảo quản tại Đền thờ Cá Ông Hội An, Đền thờ Cá Ông Đà Nẵng; Bảo tàng Viện Hải dương học.",
        "vn_status": "IUCN Red List: LC; Phụ lục II CITES.",
        "vn_literature": "Smith et al. 1995. Collection of Marine Research Works 6: 147–176. NXB Khoa học và Kỹ thuật; McGowen et al., 2021.",
        "en_size": "Length 4.5 - 6.0 m; weight 1,500 - 3,000 kg.",
        "en_distribution": "Tropical and warm-temperate deep oceans. In Vietnam: Offshore waters of Central Vietnam.",
        "en_specimen": "Whale temples in Hoi An and Da Nang; Institute of Oceanography.",
        "en_status": "IUCN: LC; CITES Appendix II.",
        "en_literature": "Smith et al., 1995; McGowen et al., 2021.",
        "conservation_status": "rare",
        "morphology_vn": "Đầu to tròn phình lớn dạng bóng bán cầu, không có mỏ. Vây lưng thấp, gốc vây rất rộng nằm lệch về phía trước 1/3 thân. Toàn thân màu đen bóng hoặc xám đen tuyền; dưới ngực có một vệt màu xám nhạt hình mỏ neo.",
        "ecology_vn": "Sống theo cấu trúc bầy đàn mẫu hệ chặt chẽ từ 15 - 50 cá thể. Thường xuyên lặn sâu 500 - 800m để săn mực ống với tốc độ phi nước đại (được ví như báo hoa mai của đại dương sâu). Thường hay mắc cạn tập thể theo đàn.",
        "economic_value_vn": "Là một trong những loài 'Cá Ông Tiêu' được tôn kính trang trọng bậc nhất tại các lăng miếu duyên hải Nam Trung Bộ.",
    },
    {
        "id": "thubien-species-30",
        "collection_id": "thu-bien",
        "volume": 1,
        "species_index": 30,
        "vn_name": "Cá hổ kình giả",
        "scientific_name": "Pseudorca crassidens",
        "authorship": "(Owen, 1846)",
        "en_common_name": "False killer whale",
        "vn_alternate_names": "Cá voi sát thủ giả",
        "tax_class_vn": "Lớp Thú (Động vật có vú)",
        "tax_class_latin": "Mammalia",
        "tax_order_vn": "Bộ Cá voi",
        "tax_order_latin": "Cetacea",
        "tax_family_vn": "Họ Cá heo mỏ",
        "tax_family_latin": "Delphinidae",
        "tax_genus_vn": "Chi Pseudorca Reinhardt, 1862",
        "tax_genus_latin": "Pseudorca Reinhardt, 1862",
        "vn_size": "Chiều dài cơ thể 4,5 - 6,0 m; khối lượng khoảng 1.200 - 2.200 kg.",
        "vn_distribution": "Việt Nam: Ghi nhận ở vùng biển miền Trung, Vịnh Bắc Bộ và Nam Bộ.",
        "vn_specimen": "Mẫu sọ bảo quản tại Đền thờ Cá Ông Hội An (HA2019-T4); Viện Hải dương học.",
        "vn_status": "IUCN Red List: NT (Gần bị đe dọa); Phụ lục II CITES.",
        "vn_literature": "Smith et al. 1995. Collection of Marine Research Works 6: 147–176. NXB Khoa học và Kỹ thuật; McGowen et al., 2021.",
        "en_size": "Length 4.5 - 6.0 m; weight 1,200 - 2,200 kg.",
        "en_distribution": "Tropical and temperate open oceans. In Vietnam: Offshore waters of Central and Southern Vietnam.",
        "en_specimen": "Whale temples in Hoi An; Institute of Oceanography.",
        "en_status": "IUCN: NT; CITES Appendix II.",
        "en_literature": "Smith et al., 1995; McGowen et al., 2021.",
        "conservation_status": "rare",
        "morphology_vn": "Thân hình thuôn dài thanh mảnh màu đen sẫm. Đầu thuôn nhỏ, trán tròn, không có mỏ. Vây ngực có khúc gập hình khuỷu tay gồ cong độc đáo. Răng to khỏe, hình nón (8 - 11 chiếc mỗi bên hàm).",
        "ecology_vn": "Sống bầy đàn tính xã hội cực cao, thường chia sẻ thức ăn cho nhau. Là động vật ăn thịt đầu bảng, săn các loài cá lớn (cá ngừ, cá buồm) và đôi khi tấn công cả các loài cá heo khác.",
        "economic_value_vn": "Có ý nghĩa nghiên cứu tập tính xã hội và sinh thái thú biển.",
    },
    {
        "id": "thubien-species-31",
        "collection_id": "thu-bien",
        "volume": 1,
        "species_index": 31,
        "vn_name": "Cá hổ kình",
        "scientific_name": "Orcinus orca",
        "authorship": "(Linnaeus, 1758)",
        "en_common_name": "Killer whale / Orca",
        "vn_alternate_names": "Cá voi sát thủ",
        "tax_class_vn": "Lớp Thú (Động vật có vú)",
        "tax_class_latin": "Mammalia",
        "tax_order_vn": "Bộ Cá voi",
        "tax_order_latin": "Cetacea",
        "tax_family_vn": "Họ Cá heo mỏ",
        "tax_family_latin": "Delphinidae",
        "tax_genus_vn": "Chi Orcinus Fitzinger, 1843",
        "tax_genus_latin": "Orcinus Fitzinger, 1843",
        "vn_size": "Thành viên lớn nhất họ Cá heo mỏ: Chiều dài con đực 7 - 9 m (khối lượng 4.000 - 7.000 kg); con cái dài 6 - 7 m (khối lượng 3.000 - 4.500 kg).",
        "vn_distribution": "Việt Nam: Ghi nhận di cư qua vùng biển khơi Biển Đông, vùng biển Hoàng Sa, Trường Sa và vùng biển Khánh Hòa, Bình Thuận.",
        "vn_specimen": "Mẫu sọ và răng lưu giữ tại Viện Hải dương học.",
        "vn_status": "IUCN Red List: DD; Phụ lục II CITES; Nghị định 64/2019/NĐ-CP.",
        "vn_literature": "Smith et al. 1995. Collection of Marine Research Works 6: 147–176. NXB Khoa học và Kỹ thuật; Reeves et al., 2002.",
        "en_size": "Males 7 - 9 m (4 - 7 tons); females 6 - 7 m (3 - 4.5 tons).",
        "en_distribution": "Cosmopolitan across all oceans. In Vietnam: South China Sea, Paracel and Spratly Islands.",
        "en_specimen": "Institute of Oceanography.",
        "en_status": "IUCN: DD; CITES Appendix II.",
        "en_literature": "Smith et al., 1995; Reeves et al., 2002.",
        "conservation_status": "rare",
        "morphology_vn": "Màu sắc đen trắng tương phản nổi bật: Lưng và sườn đen bóng, bụng trắng tuyền kéo dài lên hai bên hông; sau mắt có một đốm trắng hình bầu dục lớn; sau vây lưng có vệt 'yên ngựa' màu xám. Vây lưng con đực cao thẳng đứng hình tam giác tới 1,8 mét.",
        "ecology_vn": "Kẻ săn mồi đỉnh chóp tối thượng của đại dương: thông minh bậc nhất, săn mồi theo chiến thuật bầy đàn phối hợp cực kỳ tinh vi. Thức ăn: Cá ngừ, cá đuối, rùa biển, hải cẩu và các loài cá voi khác.",
        "economic_value_vn": "Biểu tượng đỉnh chóp của hệ sinh thái đại dương toàn cầu.",
    },
    {
        "id": "thubien-species-32",
        "collection_id": "thu-bien",
        "volume": 1,
        "species_index": 32,
        "vn_name": "Cá hổ kình lùn",
        "scientific_name": "Feresa attenuata",
        "authorship": "Gray, 1874",
        "en_common_name": "Pygmy killer whale",
        "vn_alternate_names": "Cá voi sát thủ lùn",
        "tax_class_vn": "Lớp Thú (Động vật có vú)",
        "tax_class_latin": "Mammalia",
        "tax_order_vn": "Bộ Cá voi",
        "tax_order_latin": "Cetacea",
        "tax_family_vn": "Họ Cá heo mỏ",
        "tax_family_latin": "Delphinidae",
        "tax_genus_vn": "Chi Feresa Gray, 1870",
        "tax_genus_latin": "Feresa Gray, 1870",
        "vn_size": "Chiều dài cơ thể 2,1 - 2,6 m; khối lượng khoảng 150 - 225 kg.",
        "vn_distribution": "Việt Nam: Vùng biển ngoài khơi miền Trung (Quảng Nam, Đà Nẵng, Khánh Hòa).",
        "vn_specimen": "Mẫu vật hộp sọ tại Đền thờ Cá Ông Hội An, Đà Nẵng; Viện Hải dương học.",
        "vn_status": "IUCN Red List: LC; Phụ lục II CITES.",
        "vn_literature": "Smith et al. 1995. Collection of Marine Research Works 6: 147–176. NXB Khoa học và Kỹ thuật; McGowen et al., 2021.",
        "en_size": "Length 2.1 - 2.6 m; weight 150 - 225 kg.",
        "en_distribution": "Tropical and subtropical deep oceans. In Vietnam: Central Vietnam offshore.",
        "en_specimen": "Whale temples in Hoi An and Da Nang; Institute of Oceanography.",
        "en_status": "IUCN: LC; CITES Appendix II.",
        "en_literature": "Smith et al., 1995; McGowen et al., 2021.",
        "conservation_status": "rare",
        "morphology_vn": "Thân hình thon mập, đầu tròn không có mỏ; môi có viền trắng rõ nét; vùng cằm và bụng có một mảng màu trắng xám. Vây ngực tròn đầu, vây lưng cao hình liềm.",
        "ecology_vn": "Sống thành đàn 15 - 30 cá thể ở vùng nước sâu. Thức ăn: Mực ống và các loài cá nhỏ.",
        "economic_value_vn": "Bảo tồn đa dạng sinh học thú biển nhiệt đới.",
    },
    {
        "id": "thubien-species-33",
        "collection_id": "thu-bien",
        "volume": 1,
        "species_index": 33,
        "vn_name": "Cá voi đầu dưa",
        "scientific_name": "Peponocephala electra",
        "authorship": "(Gray, 1846)",
        "en_common_name": "Melon-headed whale",
        "vn_alternate_names": "Cá voi bầu đọt",
        "tax_class_vn": "Lớp Thú (Động vật có vú)",
        "tax_class_latin": "Mammalia",
        "tax_order_vn": "Bộ Cá voi",
        "tax_order_latin": "Cetacea",
        "tax_family_vn": "Họ Cá heo mỏ",
        "tax_family_latin": "Delphinidae",
        "tax_genus_vn": "Chi Peponocephala Nishiwaki & Norris, 1966",
        "tax_genus_latin": "Peponocephala Nishiwaki & Norris, 1966",
        "vn_size": "Chiều dài cơ thể 2,4 - 2,8 m; khối lượng khoảng 180 - 260 kg.",
        "vn_distribution": "Việt Nam: Vùng biển ngoài khơi sâu Trung Bộ và vùng biển Hoàng Sa, Trường Sa.",
        "vn_specimen": "Mẫu sọ lưu giữ tại Đền thờ Cá Ông Đà Nẵng, Bình Thuận; Viện Hải dương học.",
        "vn_status": "IUCN Red List: LC; Phụ lục II CITES.",
        "vn_literature": "Smith et al. 1995. Collection of Marine Research Works 6: 147–176. NXB Khoa học và Kỹ thuật; McGowen et al., 2021.",
        "en_size": "Length 2.4 - 2.8 m; weight 180 - 260 kg.",
        "en_distribution": "Tropical oceans worldwide. In Vietnam: Offshore waters of Central Vietnam.",
        "en_specimen": "Da Nang and Binh Thuan whale temples; Institute of Oceanography.",
        "en_status": "IUCN: LC; CITES Appendix II.",
        "en_literature": "Smith et al., 1995; McGowen et al., 2021.",
        "conservation_status": "rare",
        "morphology_vn": "Đầu hình tam giác thuôn nhọn nhìn từ trên xuống giống quả dưa; trán tròn không có mỏ. Vây ngực nhọn hoắt hình liềm. Môi có viền trắng, vùng mặt có vệt sẫm hình mặt nạ.",
        "ecology_vn": "Sống theo những đàn lớn từ 100 - 500 cá thể ở vùng nước khơi sâu. Thường bơi nhanh, tạo nhiều bọt nước.",
        "economic_value_vn": "Bảo vệ sinh thái đại dương sâu.",
    },
    {
        "id": "thubien-species-34",
        "collection_id": "thu-bien",
        "volume": 1,
        "species_index": 34,
        "vn_name": "Cá heo mõm dài nhiệt đới",
        "scientific_name": "Delphinus delphis",
        "authorship": "Linnaeus, 1758",
        "en_common_name": "Common dolphin (Tropical form)",
        "vn_alternate_names": "Cá heo thông thường, Cá heo sọc vàng",
        "tax_class_vn": "Lớp Thú (Động vật có vú)",
        "tax_class_latin": "Mammalia",
        "tax_order_vn": "Bộ Cá voi",
        "tax_order_latin": "Cetacea",
        "tax_family_vn": "Họ Cá heo mỏ",
        "tax_family_latin": "Delphinidae",
        "tax_genus_vn": "Chi Cá heo Delphinus Linnaeus, 1758",
        "tax_genus_latin": "Delphinus Linnaeus, 1758",
        "vn_size": "Chiều dài cơ thể 2,1 - 2,5 m; khối lượng khoảng 80 - 130 kg.",
        "vn_distribution": "Việt Nam: Vùng biển ngoài khơi miền Trung và Nam Bộ (ghi nhận phân loài Delphinus delphis tropicalis).",
        "vn_specimen": "Mẫu vật hộp sọ giám định tại Đền thờ Cá Ông Hội An, Đà Nẵng; Viện Hải dương học.",
        "vn_status": "IUCN Red List: LC; Phụ lục II CITES.",
        "vn_literature": "Smith et al. 1995. Collection of Marine Research Works 6: 147–176. NXB Khoa học và Kỹ thuật; McGowen et al., 2021. Raffles Bull Zool 69: 481–496.",
        "en_size": "Length 2.1 - 2.5 m; weight 80 - 130 kg.",
        "en_distribution": "Warm temperate and tropical waters. In Vietnam: Central offshore (subspecies D. d. tropicalis).",
        "en_specimen": "Whale temples in Central Vietnam; Institute of Oceanography.",
        "en_status": "IUCN: LC; CITES Appendix II.",
        "en_literature": "Smith et al., 1995; McGowen et al., 2021.",
        "conservation_status": "rare",
        "morphology_vn": "Mẫu hoa văn đồng hồ cát (hourglass pattern) hai bên thân độc đáo: Phần phía trước ngực có màu vàng thổ hoàng nhạt, phần phía sau có màu xám nhạt, giao nhau ở dưới vây lưng. Mỏ dài hẹp, răng nhiều (40 - 55 chiếc mỗi bên hàm).",
        "ecology_vn": "Sống bầy đàn lớn, bơi lội năng động với tốc độ cao, thường nhào lộn và lướt sóng mũi tàu thuyền.",
        "economic_value_vn": "Chỉ thị nguồn lợi cá nổi đại dương.",
    },
]

# ── 4. Thực thi Upsert Loài ───────────────────────────────────────────
def upsert_species():
    print(f"\n--- 3. UPSERT {len(MARINE_MAMMALS)} LOÀI THÚ BIỂN VÀO SUPABASE ---")
    url = f"{SUPABASE_URL}/rest/v1/species"
    
    success = 0
    errors = 0
    
    for sp in MARINE_MAMMALS:
        sp_id = sp["id"]
        sci_name = sp["scientific_name"]
        vn_name = sp["vn_name"]
        
        req = urllib.request.Request(
            f"{url}?on_conflict=id",
            headers={**HEADERS_SUPA, "Prefer": "resolution=merge-duplicates,return=representation"},
            data=json.dumps(sp).encode("utf-8"),
            method="POST"
        )
        try:
            with urllib.request.urlopen(req) as r:
                res = json.loads(r.read().decode("utf-8"))
                print(f"  ✅ [{sp['species_index']:02d}/34] {sp_id} | {vn_name} ({sci_name})")
                success += 1
        except urllib.error.HTTPError as e:
            print(f"  ❌ [{sp['species_index']:02d}/34] Lỗi {sp_id}: {e} - {e.read().decode('utf-8')}")
            errors += 1
        except Exception as e:
            print(f"  ❌ [{sp['species_index']:02d}/34] Lỗi {sp_id}: {e}")
            errors += 1
            
    print(f"\n🎯 KẾT QUẢ: Thành công {success}/{len(MARINE_MAMMALS)} loài. Lỗi: {errors}.")

if __name__ == "__main__":
    print("🐳 BẮT ĐẦU KHỞI TẠO COLLECTION & UPSERT THÚ BIỂN VIỆT NAM 🐳")
    setup_collection()
    setup_literature()
    upsert_species()
    print("\n🏁 HOÀN TẤT BƯỚC ① (UPSERT SPECIES). SẴN SÀNG CHUYỂN SANG BƯỚC ② (WORMS SYNC).")
